<template>
  <section class="mandate-workspace">
    <div class="workspace-head">
      <div><h2>出租委託</h2><p>管理業主單位的出租委託審核與服務狀態。</p></div>
      <button class="primary-btn" @click="showCreate = true">建立委託</button>
    </div>
    <div class="summary-grid">
      <div v-for="card in summaryCards" :key="card.key" class="summary-card"><span>{{ card.label }}</span><strong>{{ summary[card.key] || 0 }}</strong></div>
    </div>
    <div class="toolbar"><input v-model="keyword" placeholder="搜尋委託編號、業主或單位" @keyup.enter="load" /><select v-model="status" @change="load"><option value="">全部狀態</option><option value="draft">草稿</option><option value="pending_review">待審核</option><option value="active">啟用</option><option value="suspended">暫停</option><option value="terminated">已終止</option></select><button @click="load">重新載入</button></div>
    <div class="table-wrap"><table><thead><tr><th>委託編號</th><th>業主 / 單位</th><th>委託期間</th><th>負責人</th><th>狀態</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id" @click="select(item)"><td>{{ item.mandateNo }}</td><td>{{ item.ownerName }}<br /><small>{{ item.projectName }} · {{ item.unitNo }}</small></td><td>{{ item.startDate }}<br />{{ item.endDate || '未設定' }}</td><td>{{ item.responsibleUserName || '未指派' }}</td><td><span class="status" :class="item.status">{{ statusLabel(item.status) }}</span></td><td class="actions"><button v-if="item.status === 'draft'" @click.stop="submit(item)">提交</button><button v-if="item.status === 'pending_review'" @click.stop="openReview(item)">審核</button><button v-if="item.status === 'active'" @click.stop="changeStatus(item, 'suspended')">暫停</button><button v-if="item.status === 'suspended'" @click.stop="changeStatus(item, 'active')">恢復</button><button v-if="['active','suspended'].includes(item.status)" @click.stop="terminate(item)">終止</button></td></tr><tr v-if="!items.length"><td colspan="6" class="empty">暫無委託資料</td></tr></tbody></table></div>
    <aside v-if="selected" class="detail-panel"><div class="detail-head"><h3>{{ selected.mandateNo }}</h3><button @click="selected = null">關閉</button></div><p>{{ selected.ownerName }} · {{ selected.projectName }} · {{ selected.unitNo }}</p><p>委託期間：{{ selected.startDate }} 至 {{ selected.endDate || '未設定' }}</p><p>管理費：{{ selected.managementFee || 0 }}　佣金：{{ selected.commissionPercent || 0 }}%</p><button v-if="['active','suspended'].includes(selected.status)" @click="openHandover">{{ handover ? '編輯接管資料' : '建立接管資料' }}</button><p v-if="handover" class="handover-state">接管狀態：{{ handover.status === 'completed' ? '已完成' : '草稿' }} · {{ handover.handoverDate }}</p><h4>文件附件</h4><div class="upload-row"><select v-model="documentType"><option value="mandate_document">委託書</option><option value="authorization">授權文件</option><option value="handover_photo">交接照片</option><option value="inventory">設備清單</option></select><input type="file" @change="uploadDocument" /></div><ul><li v-for="doc in documents" :key="doc.id"><button class="link-btn" @click="downloadDocument(doc)">{{ doc.originalName }}</button><small>{{ doc.relationType }} · {{ doc.createdAt }}</small></li><li v-if="!documents.length">尚無附件</li></ul><h4>狀態歷史</h4><ul><li v-for="entry in history" :key="entry.id">{{ entry.fromStatus || '—' }} → {{ entry.toStatus }} · {{ entry.changedAt }}<small v-if="entry.reason">（{{ entry.reason }}）</small></li></ul></aside>
    <div v-if="showCreate" class="modal-backdrop"><div class="modal"><div class="detail-head"><h3>建立出租委託</h3><button @click="showCreate = false">關閉</button></div><label>營運中單位<select v-model="form.ownerUnitId"><option :value="null">請選擇</option><option v-for="unit in options.units" :key="unit.id" :value="unit.id">{{ unit.projectName }} · {{ unit.unitNo }} · {{ unit.ownerName }}</option></select></label><label>委託類型<select v-model="form.mandateType"><option value="management">一般管理</option><option value="exclusive">獨家委託</option><option value="non_exclusive">非獨家委託</option></select></label><div class="form-grid"><label>開始日期<input v-model="form.startDate" type="date" /></label><label>結束日期<input v-model="form.endDate" type="date" /></label><label>管理費<input v-model="form.managementFee" type="number" min="0" step="0.01" /></label><label>佣金比例<input v-model="form.commissionPercent" type="number" min="0" max="100" step="0.01" /></label></div><label>負責人<select v-model="form.responsibleUserId"><option :value="null">未指派</option><option v-for="user in options.users" :key="user.id" :value="user.id">{{ user.displayName }}</option></select></label><button class="primary-btn" @click="create">儲存草稿</button></div></div>
    <div v-if="reviewing" class="modal-backdrop"><div class="modal"><h3>審核委託 {{ reviewing.mandateNo }}</h3><textarea v-model="reviewNote" placeholder="審核備註"></textarea><div class="modal-actions"><button @click="review(false)">退回</button><button class="primary-btn" @click="review(true)">核准並啟用</button></div></div></div>
    <div v-if="showHandover" class="modal-backdrop"><div class="modal"><h3>物件接管 · {{ selected && selected.mandateNo }}</h3><div class="form-grid"><label>交接日期<input v-model="handoverForm.handoverDate" type="date" /></label><label>交接人<input v-model="handoverForm.receivedBy" /></label><label>鑰匙數量<input v-model.number="handoverForm.keyCount" type="number" min="0" /></label><label>門卡數量<input v-model.number="handoverForm.accessCardCount" type="number" min="0" /></label><label>水錶讀數<input v-model="handoverForm.waterMeter" /></label><label>電錶讀數<input v-model="handoverForm.electricityMeter" /></label></div><label>屋況摘要<textarea v-model="handoverForm.conditionSummary"></textarea></label><label>設備清單（JSON）<textarea v-model="handoverForm.inventory"></textarea></label><label>備註<textarea v-model="handoverForm.notes"></textarea></label><div class="modal-actions"><button @click="showHandover = false">取消</button><button @click="saveHandover(false)">儲存草稿</button><button class="primary-btn" @click="saveHandover(true)">完成接管</button></div></div></div>
  </section>
</template>

<script>
import { fetchAdminRentalMandates, fetchAdminRentalMandateOptions, createAdminRentalMandate, submitAdminRentalMandate, reviewAdminRentalMandate, updateAdminRentalMandateStatus, fetchAdminRentalMandateHistory, fetchAdminPropertyHandover, saveAdminPropertyHandover, fetchAdminRentalMandateDocuments, uploadAdminRentalMandateDocument, downloadAdminRentalMandateDocument } from '../services/propertyApi';
export default {
  name: 'AdminRentalMandateWorkspace',
  props: { page: { type: Object, default: () => ({}) } },
  data() { return { items: [], summary: {}, options: { units: [], users: [] }, selected: null, history: [], handover: null, documents: [], documentType: 'mandate_document', showHandover: false, handoverForm: {}, keyword: '', status: '', showCreate: false, reviewing: null, reviewNote: '', form: { ownerUnitId: null, mandateType: 'management', startDate: '', endDate: '', managementFee: 0, commissionPercent: 0, responsibleUserId: null } }; },
  computed: { summaryCards() { return [{ key: 'total', label: '全部委託' }, { key: 'draft', label: '草稿' }, { key: 'pendingReview', label: '待審核' }, { key: 'active', label: '啟用中' }, { key: 'suspended', label: '暫停' }]; } },
  watch: { 'page.adminRentalMandateCreateNonce': 'openCreate', 'page.adminRentalMandateRefreshNonce': 'load' },
  mounted() { this.load(); this.loadOptions(); },
  methods: {
    async load() { try { const data = await fetchAdminRentalMandates({ keyword: this.keyword, status: this.status, page: 1, pageSize: 100 }); this.items = data.items || []; this.summary = data.summary || {}; if (this.selected) this.select(this.items.find(item => item.id === this.selected.id) || null); } catch (error) { this.$emit('toast', error.message); } },
    async loadOptions() { try { this.options = await fetchAdminRentalMandateOptions(); } catch (error) { this.$emit('toast', error.message); } },
    openCreate() { this.showCreate = true; },
    async create() { try { await createAdminRentalMandate({ ...this.form, ownerUnitId: Number(this.form.ownerUnitId), responsibleUserId: this.form.responsibleUserId ? Number(this.form.responsibleUserId) : null }); this.showCreate = false; this.$emit('toast', '委託草稿已建立'); await this.load(); } catch (error) { this.$emit('toast', error.message); } },
    async submit(item) { try { await submitAdminRentalMandate(item.id); this.$emit('toast', '已提交審核'); await this.load(); } catch (error) { this.$emit('toast', error.message); } },
    openReview(item) { this.reviewing = item; this.reviewNote = ''; },
    async review(approved) { try { await reviewAdminRentalMandate(this.reviewing.id, { approved, note: this.reviewNote }); this.reviewing = null; this.$emit('toast', approved ? '委託已核准並啟用' : '委託已退回'); await this.load(); } catch (error) { this.$emit('toast', error.message); } },
    async changeStatus(item, nextStatus) { try { await updateAdminRentalMandateStatus(item.id, { status: nextStatus, reason: '' }); await this.load(); } catch (error) { this.$emit('toast', error.message); } },
    async terminate(item) { const reason = window.prompt('請輸入終止原因'); if (!reason) return; try { await updateAdminRentalMandateStatus(item.id, { status: 'terminated', reason }); await this.load(); } catch (error) { this.$emit('toast', error.message); } },
    async select(item) { this.selected = item; this.handover = null; this.documents = []; if (!item) return; this.history = (await fetchAdminRentalMandateHistory(item.id)) || []; this.handover = await fetchAdminPropertyHandover(item.id); this.documents = (await fetchAdminRentalMandateDocuments(item.id)) || []; },
    openHandover() { this.handoverForm = { handoverDate: this.handover?.handoverDate || new Date().toISOString().slice(0, 10), conditionSummary: this.handover?.conditionSummary || '', keyCount: this.handover?.keyCount || 0, accessCardCount: this.handover?.accessCardCount || 0, waterMeter: this.handover?.waterMeter || '', electricityMeter: this.handover?.electricityMeter || '', inventory: this.handover?.inventory || '{}', receivedBy: this.handover?.receivedBy || '', notes: this.handover?.notes || '' }; this.showHandover = true; },
    async saveHandover(completed) { try { this.handover = await saveAdminPropertyHandover(this.selected.id, { ...this.handoverForm, completed }); this.showHandover = false; this.$emit('toast', completed ? '接管資料已完成' : '接管草稿已儲存'); } catch (error) { this.$emit('toast', error.message); } },
    async uploadDocument(event) { const file = event.target.files?.[0]; if (!file || !this.selected) return; try { this.documents = await uploadAdminRentalMandateDocument(this.selected.id, this.documentType, file); this.$emit('toast', '附件已上傳'); } catch (error) { this.$emit('toast', error.message); } finally { event.target.value = ''; } },
    async downloadDocument(doc) { try { const result = await downloadAdminRentalMandateDocument(this.selected.id, doc.id); const url = URL.createObjectURL(result.blob); const link = document.createElement('a'); link.href = url; link.download = doc.originalName; link.click(); URL.revokeObjectURL(url); } catch (error) { this.$emit('toast', error.message); } },
    statusLabel(status) { return { draft: '草稿', pending_review: '待審核', active: '啟用', suspended: '暫停', terminated: '已終止' }[status] || status; }
  }
};
</script>

<style scoped>
.mandate-workspace{position:relative}.workspace-head,.detail-head,.toolbar,.modal-actions{display:flex;align-items:center;justify-content:space-between;gap:12px}.workspace-head{margin-bottom:18px}.workspace-head h2{margin:0}.workspace-head p{margin:5px 0;color:#718096}.primary-btn{background:#2563eb;color:white;border:0;border-radius:6px;padding:9px 14px}.summary-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:18px}.summary-card{padding:14px;background:#f7fafc;border:1px solid #e2e8f0;border-radius:8px}.summary-card span{display:block;color:#718096;font-size:13px}.summary-card strong{font-size:24px}.toolbar{justify-content:flex-start;margin-bottom:12px}.toolbar input{flex:1}.toolbar input,.toolbar select,.toolbar button,.modal input,.modal select,.modal textarea{border:1px solid #cbd5e1;border-radius:5px;padding:8px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px;border-bottom:1px solid #edf2f7}tbody tr{cursor:pointer}.actions button{margin-right:6px;border:0;background:#edf2f7;padding:5px 8px;border-radius:4px}.status{padding:4px 8px;border-radius:10px;font-size:12px;background:#e2e8f0}.status.active{background:#dcfce7;color:#166534}.status.pending_review{background:#fef3c7;color:#92400e}.status.terminated{background:#fee2e2;color:#991b1b}.empty{text-align:center;color:#718096}.detail-panel{position:absolute;right:0;top:60px;width:340px;background:white;border:1px solid #cbd5e1;border-radius:8px;padding:18px;box-shadow:0 12px 30px #0002;z-index:2}.detail-panel ul{padding-left:18px}.detail-panel li{margin-bottom:8px}.modal-backdrop{position:fixed;inset:0;background:#0006;display:grid;place-items:center;z-index:10}.modal{background:white;border-radius:10px;padding:22px;width:min(560px,92vw);display:grid;gap:14px}.modal label{display:grid;gap:5px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.modal textarea{min-height:100px}
.upload-row{display:flex;gap:6px;align-items:center}.upload-row select{max-width:120px}.link-btn{border:0;background:none;color:#2563eb;padding:0;cursor:pointer}.detail-panel li small{display:block;color:#718096}.handover-state{color:#166534}
</style>
