<template>
  <section class="content-grid admin-finance-workspace admin-reserve-finance-workspace">
    <div class="panel table-panel finance-review-panel">
      <div class="panel-head"><div><h2>{{ viewMode === 'pending' ? $t('legacy.t_43c2a2479314') : $t('legacy.t_b1f8cd5cfec5') }}</h2><span>{{ totalRows }} {{ $t('legacy.t_40c977e2b5b2') }} {{ viewMode === 'pending' ? $t('legacy.t_efe2af01ea25') : $t('legacy.t_98d2a03e4949') }}</span></div><div class="finance-list-actions"><span v-if="selectedIds.length">{{ $t('legacy.t_06fb19973447') }} {{ selectedIds.length }} {{ $t('legacy.t_d0bb9b2b8ea7') }}</span><span v-if="loading">{{ $t('legacy.t_6ce3778a43cd') }}</span><template v-if="viewMode === 'history'"><button type="button" class="history-batch-button" :disabled="!selectedIds.length || batchBusy" @click="batchDownload('invoice')">批量下载发票</button><button type="button" class="history-batch-button" :disabled="!selectedIds.length || batchBusy" @click="batchDownload('receipt')">批量下载收据</button><button type="button" class="history-batch-button danger" :disabled="!selectedReopenIds.length || actionSaving" @click="openBatchReopen">批量退回</button></template></div></div>
      <div v-if="errorMessage" class="admin-owner-state error"><strong>{{ $t('legacy.t_a56234453671') }}</strong><span>{{ errorMessage }}</span><button @click="loadData">{{ $t('legacy.t_0c9157b5bfac') }}</button></div>
      <div v-else class="table-wrap finance-review-table-wrap">
        <table>
          <thead><tr><th class="finance-check-cell"><input type="checkbox" :checked="allSelectableSelected" :disabled="!selectableRows.length" @change="toggleSelectablePage"></th><th>{{ $t('legacy.t_32e88cf956f6') }}</th><th>{{ $t('legacy.t_114246450ff0') }}</th><th>{{ $t('legacy.t_d61f1eba334a') }}</th><th>{{ $t('legacy.t_3542cc1d606d') }}</th><th>{{ $t('legacy.t_058f511c98cf') }}</th><th>{{ $t('legacy.t_41ee43593eb7') }}</th><th>{{ $t('legacy.t_4feb65fa9683') }}</th><th>{{ $t('legacy.t_94007fdd6e4e') }}</th><th>{{ $t('legacy.t_f3ea6d345e2a') }}</th></tr></thead>
          <tbody>
            <tr v-for="row in rows" :key="row.id" :class="{ selected: row.id === selectedId }" @click="selectRow(row)">
              <td class="finance-check-cell"><input v-if="viewMode === 'history' || row.confirmationStatus === 'pending'" v-model="selectedIds" type="checkbox" :value="row.id" @click.stop></td>
              <td><strong>{{ row.transactionNo }}</strong><small>{{ row.receiptNo || $t('legacy.t_4842630ef72e') }}</small></td>
              <td>{{ row.projectName }}<small>{{ row.unitNo }}</small></td>
              <td>{{ row.payerName || '—' }}<small>{{ row.bankReference || '—' }}</small></td>
              <td><b>{{ row.currency || 'MYR' }} {{ money(row.amount) }}</b></td>
              <td>{{ displayDate(row.transactionDate) }}</td>
              <td><button class="finance-proof-link" :disabled="!row.proofDocumentId" @click.stop="selectAndOpenProof(row)">{{ row.proofDocumentId ? $t('legacy.t_16194d3fdaa8') : $t('legacy.t_08f9d55c4a07') }}</button></td>
              <td><span class="tag" :class="confirmationClass(row.confirmationStatus)">{{ confirmationLabel(row.confirmationStatus) }}</span></td>
              <td><span class="tag" :class="syncClass(row.syncStatus)">{{ syncLabel(row.syncStatus) }}</span></td>
              <td><button type="button" class="finance-detail-button" @click.stop="openDetails(row)">查看详情</button></td>
            </tr>
            <tr v-if="!loading && !rows.length"><td colspan="10" class="admin-owner-empty">{{ $t('legacy.t_43c0d81f0705') }}</td></tr>
          </tbody>
        </table>
      </div>
      <div class="pager"><span>{{ $t('legacy.t_3b6ef811b85a') }} {{ totalRows }} {{ $t('legacy.t_86761b63a7bd') }}</span><div class="admin-building-pager"><button :disabled="pageNumber <= 1" @click="goPage(pageNumber - 1)">&lt;</button><button v-for="n in visiblePages" :key="n" :class="{ active: n === pageNumber }" @click="goPage(n)">{{ n }}</button><button :disabled="pageNumber >= totalPages" @click="goPage(pageNumber + 1)">&gt;</button><select v-model.number="pageSize"><option :value="10">{{ $t('legacy.t_fc6da0e815a1') }}</option><option :value="20">{{ $t('legacy.t_93d673672fa5') }}</option><option :value="50">{{ $t('legacy.t_529930b886d2') }}</option></select></div></div>
    </div>

    <dialog ref="detailDialog" class="modal finance-record-detail-dialog">
      <template v-if="selectedRow">
        <div class="modal-head"><div><h3>预备金确认详情</h3><small>{{ selectedRow.transactionNo }}</small></div><button type="button" class="icon-close" @click="closeDetails">×</button></div>
        <div class="finance-record-detail-body detail-card">
        <div class="profile finance-review-profile"><div class="big-avatar">{{ $t('legacy.t_aab9b3921100') }}</div><div class="finance-review-profile-copy"><h3>{{ selectedRow.transactionNo }}</h3><p>{{ selectedRow.projectName }} · {{ selectedRow.unitNo }}</p></div><span class="tag" :class="confirmationClass(selectedRow.confirmationStatus)">{{ confirmationLabel(selectedRow.confirmationStatus) }}</span></div>
        <div class="detail-actions finance-review-actions">
          <button :disabled="!selectedRow.proofDocumentId" @click="openProofFromDetails">{{ $t('legacy.t_96bd7ca72147') }}</button>
          <a v-if="viewMode === 'history'" class="finance-document-button" :href="documentUrl(selectedRow, 'invoice')" download>Invoice / 发票</a>
          <a v-if="viewMode === 'history'" class="finance-document-button" :href="documentUrl(selectedRow, 'receipt')" download>Official Receipt / 收据</a>
          <button v-if="viewMode === 'history' && selectedRow.confirmationStatus === 'confirmed'" class="reject" @click="openReopenFromDetails">{{ $t('finance.reopen') }}</button>
          <button v-if="selectedRow.confirmationStatus === 'pending'" class="confirm" @click="openDecisionFromDetails(true)">{{ $t('legacy.t_813b101df66f') }}</button>
          <button v-if="selectedRow.confirmationStatus === 'pending'" class="reject" @click="openDecisionFromDetails(false)">{{ $t('legacy.t_f21a4e73212a') }}</button>
        </div>
        <div class="detail-section"><h4><span class="num">{{ $t('legacy.t_356a192b7913') }}</span>{{ $t('legacy.t_82c8aa737dd5') }}</h4><div class="kv"><span>{{ $t('legacy.t_d61f1eba334a') }}</span><b>{{ selectedRow.payerName || '—' }}</b></div><div class="kv"><span>{{ $t('legacy.t_c6b9a8cfdb21') }}</span><b>{{ paymentMethodLabel(selectedRow.paymentMethod) }}</b></div><div class="kv"><span>{{ $t('legacy.t_bf8928021bb1') }}</span><b>{{ selectedRow.bankReference || '—' }}</b></div><div class="kv"><span>{{ $t('legacy.t_3542cc1d606d') }}</span><b>{{ selectedRow.currency }} {{ money(selectedRow.amount) }}</b></div></div>
        <div class="detail-section"><h4><span class="num">{{ $t('legacy.t_da4b9237bacc') }}</span>{{ $t('legacy.t_1efb9c79ecf7') }}</h4><div class="kv"><span>{{ $t('legacy.t_3d5edc260de1') }}</span><b>{{ $t('legacy.t_5e7b60c626a4') }} {{ money(selectedRow.accountBalance) }}</b></div><div class="kv"><span>{{ $t('legacy.t_c7e82f3b6404') }}</span><b>{{ $t('legacy.t_5e7b60c626a4') }} {{ money(selectedRow.accountMinimumBalance) }}</b></div><div class="kv"><span>{{ $t('legacy.t_0e267b2bee08') }}</span><b class="reserve-after">{{ $t('legacy.t_5e7b60c626a4') }} {{ money(Number(selectedRow.accountBalance || 0) + (selectedRow.confirmationStatus === 'pending' ? Number(selectedRow.amount || 0) : 0)) }}</b></div></div>
        <div class="detail-section"><h4><span class="num">{{ $t('legacy.t_77de68daecd8') }}</span>{{ $t('legacy.t_544d471b0705') }}</h4><div class="kv"><span>{{ $t('legacy.t_e2339796356e') }}</span><b>{{ selectedRow.proofName || $t('legacy.t_08f9d55c4a07') }}</b></div><div class="kv"><span>{{ $t('legacy.t_bffa37080afa') }}</span><b>{{ selectedRow.confirmedByName || '—' }}</b></div><div class="kv"><span>{{ $t('legacy.t_2d36c3ab208f') }}</span><b>{{ dateTime(selectedRow.confirmedAt) }}</b></div><div class="kv"><span>{{ $t('legacy.t_098de965a383') }}</span><b>{{ selectedRow.reviewNote || '—' }}</b></div></div>
        <FinanceAllocationNoteEditor :record="selectedRow" @saved="loadData" />
        </div>
      </template>
    </dialog>

    <dialog ref="decisionDialog" class="modal admin-finance-decision-dialog"><form method="dialog" @submit.prevent="submitDecision"><div class="modal-head"><div><h3>{{ approving ? $t('legacy.t_d4c367acb3b4') : $t('legacy.t_6daef0b6e930') }}</h3><small>{{ selectedRow?.transactionNo }} {{ $t('legacy.t_6287ccc52c97') }} {{ money(selectedRow?.amount) }}</small></div><button type="button" class="icon-close" @click="closeDecision">×</button></div><div class="finance-decision-body"><div :class="['finance-decision-warning', { success: approving }]"><strong>{{ approving ? $t('legacy.t_f4e8b8b461db') : $t('legacy.t_ec6e1980eaf8') }}</strong><span>{{ approving ? `賬戶餘額將增加 RM ${money(selectedRow?.amount)}` : $t('legacy.t_2f5741d5285b') }}</span></div><label v-if="approving">财务入账日期<input v-model="decisionDate" type="date" :max="today" required><small>余额与关联流水将使用此最终入账日期。</small></label><label>{{ $t('legacy.t_098de965a383') }}<textarea v-model.trim="decisionNote" maxlength="500" required :placeholder="approving ? $t('legacy.t_c333960469a4') : $t('legacy.t_f8c08ef26a07')"></textarea></label><p v-if="actionError" class="admin-property-error">{{ actionError }}</p></div><menu><button type="button" @click="closeDecision">{{ $t('legacy.t_4d0b4688c787') }}</button><button class="primary-btn" :class="{ reject: !approving }" :disabled="actionSaving">{{ actionSaving ? $t('legacy.t_1e038f9b55ec') : approving ? $t('legacy.t_37786d40f2c5') : $t('legacy.t_559f15fd1a6a') }}</button></menu></form></dialog>

    <dialog ref="batchDialog" class="modal admin-finance-decision-dialog"><form method="dialog" @submit.prevent="submitBatch"><div class="modal-head"><div><h3>{{ $t('legacy.t_6bdd44210e06') }}</h3><small>已自动带入 {{ selectedIds.length }} 笔待确认充值</small></div><button type="button" class="icon-close" @click="closeBatch">×</button></div><div class="finance-decision-body"><div class="finance-batch-overview"><span>确认记录<b>{{ batchRows.length }} 笔</b></span><span>合计金额<b>MYR {{ money(batchTotal) }}</b></span></div><div class="finance-decision-warning success"><strong>当前列表已自动带入</strong><span>核对汇总信息后可一次确认，无需逐笔操作。</span></div><label>财务入账日期<input v-model="batchDate" type="date" :max="today" required></label><label>{{ $t('legacy.t_c5dc4a6f6bc8') }}<textarea v-model.trim="batchNote" maxlength="500" required></textarea></label><p v-if="actionError" class="admin-property-error">{{ actionError }}</p></div><menu><button type="button" @click="closeBatch">{{ $t('legacy.t_4d0b4688c787') }}</button><button class="primary-btn" :disabled="actionSaving">{{ actionSaving ? $t('legacy.t_03fc655d6daf') : `一键确认 ${selectedIds.length} 笔充值` }}</button></menu></form></dialog>

    <dialog ref="reopenDialog" class="modal admin-finance-decision-dialog"><form method="dialog" @submit.prevent="submitReopen"><div class="modal-head"><div><h3>{{ $t('finance.reopenTitle') }}</h3><small>{{ selectedRow?.transactionNo }}</small></div><button type="button" class="icon-close" @click="closeReopen">×</button></div><div class="finance-decision-body"><div class="finance-decision-warning"><strong>{{ $t('finance.reopen') }}</strong><span>{{ $t('finance.reopenHint') }}</span></div><label>{{ $t('finance.reopenNote') }}<textarea v-model.trim="reopenNote" maxlength="500" required :placeholder="$t('finance.reopenNotePlaceholder')"></textarea></label><p v-if="actionError" class="admin-property-error">{{ actionError }}</p></div><menu><button type="button" @click="closeReopen">{{ $t('legacy.t_4d0b4688c787') }}</button><button class="primary-btn reject" :disabled="actionSaving">{{ actionSaving ? $t('legacy.t_1e038f9b55ec') : $t('finance.reopen') }}</button></menu></form></dialog>

    <dialog ref="batchReopenDialog" class="modal admin-finance-decision-dialog"><form method="dialog" @submit.prevent="submitBatchReopen"><div class="modal-head"><div><h3>批量退回待确认</h3><small>本次将退回 {{ selectedReopenIds.length }} 笔已确认充值</small></div><button type="button" class="icon-close" @click="closeBatchReopen">×</button></div><div class="finance-decision-body"><div class="finance-decision-warning"><strong>批量退回后重新核对</strong><span>任一记录无法退回时，本次操作将整体取消。</span></div><label>退回原因<textarea v-model.trim="batchReopenNote" maxlength="500" required placeholder="请填写本次批量退回原因"></textarea></label><p v-if="actionError" class="admin-property-error">{{ actionError }}</p></div><menu><button type="button" @click="closeBatchReopen">取消</button><button class="primary-btn reject" :disabled="actionSaving">{{ actionSaving ? '处理中…' : `退回 ${selectedReopenIds.length} 笔` }}</button></menu></form></dialog>

    <dialog ref="proofDialog" class="modal admin-finance-proof-dialog"><div class="modal-head"><div><h3>{{ $t('legacy.t_849b273896de') }}</h3><small>{{ selectedRow?.proofName || selectedRow?.transactionNo }}</small></div><button type="button" class="icon-close" @click="closeProof">×</button></div><div class="finance-proof-viewer"><div v-if="proofLoading" class="admin-owner-state">{{ $t('legacy.t_38e6a8f0a0f3') }}</div><img v-else-if="proofUrl && selectedRow?.proofMimeType?.startsWith('image/')" :src="proofUrl" :alt="$t('legacy.t_849b273896de')"><iframe v-else-if="proofUrl && selectedRow?.proofMimeType === 'application/pdf'" :src="proofUrl" :title="$t('legacy.t_32540522e657')"></iframe><div v-else class="admin-owner-state">{{ proofError || $t('legacy.t_410b7e2a33ff') }}</div></div><menu><button @click="closeProof">{{ $t('legacy.t_ddc05404b0d6') }}</button><button class="primary-btn" :disabled="!selectedRow?.proofDocumentId" @click="downloadProof">{{ $t('legacy.t_fb332e3c9ee6') }}</button></menu></dialog>
  </section>
</template>

<script>
import { batchConfirmAdminFinanceReviews, batchReopenAdminFinanceReviews, confirmAdminFinanceReview, downloadAdminFinanceDocuments, fetchAdminFinanceProjects, fetchAdminFinanceReviews, fetchAdminReserveProof, getAdminFinanceDocumentUrl, rejectAdminFinanceReview, reopenAdminFinanceReview } from '../services/propertyApi';
import FinanceAllocationNoteEditor from './FinanceAllocationNoteEditor.vue';
import { formatDate, formatDateTime, todayIsoDate } from '../utils/dateFormat';

export default {
  components: { FinanceAllocationNoteEditor },
  inject: ['page'],
  data() { return { rows: [], selectedId: null, selectedIds: [], pageNumber: 1, pageSize: 10, totalRows: 0, totalPages: 1, loading: false, errorMessage: '', serial: 0, approving: true, decisionDate: todayIsoDate(), batchDate: todayIsoDate(), today: todayIsoDate(), decisionNote: '', batchNote: '充值资料与银行入账信息核对一致', reopenNote: '', batchReopenNote: '', actionSaving: false, actionError: '', batchBusy: false, proofLoading: false, proofError: '', proofUrl: '' }; },
  computed: {
    selectedRow() { return this.rows.find(row => row.id === this.selectedId) || this.rows[0] || null; },
    viewMode() { return this.page.adminFinanceViewMode === 'history' ? 'history' : 'pending'; },
    pendingRows() { return this.rows.filter(row => row.confirmationStatus === 'pending'); },
    selectableRows() { return this.viewMode === 'history' ? this.rows : this.pendingRows; },
    batchRows() { return this.rows.filter(row => this.selectedIds.includes(row.id)); },
    batchTotal() { return this.batchRows.reduce((sum, row) => sum + Number(row.amount || 0), 0); },
    allSelectableSelected() { return this.selectableRows.length > 0 && this.selectableRows.every(row => this.selectedIds.includes(row.id)); },
    selectedReopenIds() { return this.rows.filter(row => this.selectedIds.includes(row.id) && row.confirmationStatus === 'confirmed').map(row => row.id); },
    visiblePages() { const start = Math.max(1, Math.min(this.pageNumber - 2, this.totalPages - 4)); return Array.from({ length: Math.min(5, this.totalPages) }, (_, i) => start + i); },
    batchNonce() { return this.page.adminFinanceBatchNonce; }, refreshNonce() { return this.page.adminFinanceRefreshNonce; }
  },
  watch: {
    'page.moduleSearch'() { this.resetLoad(); }, 'page.globalSearch'() { this.resetLoad(); }, 'page.projectFilter'() { this.resetLoad(); }, 'page.statusFilter'() { this.resetLoad(); }, 'page.adminFinanceViewMode'() { this.resetLoad(); }, 'page.dateStart'() { this.resetLoad(); }, 'page.dateEnd'() { this.resetLoad(); }, pageSize() { this.resetLoad(); },
    batchNonce(v, old) { if (v > old) this.openBatch(); }, refreshNonce(v, old) { if (v > old) this.loadData(); },
    rows: { deep: true, handler(rows) { if (!rows.some(row => row.id === this.selectedId)) this.selectedId = rows[0]?.id || null; } }
  },
  mounted() { this.loadData(); }, beforeUnmount() { this.revokeProof(); },
  methods: {
    async loadData() { const serial = ++this.serial; this.loading = true; this.errorMessage = ''; try { const params = { type: 'reserve', page: this.pageNumber, pageSize: this.pageSize, keyword: this.page.globalSearch || this.page.moduleSearch || '', projectName: String(this.page.projectFilter || '').includes('全部') ? '' : this.page.projectFilter, status: this.requestStatus(), startDate: this.page.dateStart, endDate: this.page.dateEnd }; const [response, projects] = await Promise.all([fetchAdminFinanceReviews(params), fetchAdminFinanceProjects('reserve')]); if (serial !== this.serial) return; this.rows = response.rows || []; this.totalRows = response.page?.totalRows || 0; this.totalPages = response.page?.totalPages || 1; this.pageNumber = response.page?.page || 1; this.page.adminFinanceProjects = projects || []; this.page.adminFinanceMetrics = this.metrics(response.summary || {}); this.selectedIds = this.selectedIds.filter(id => this.rows.some(row => row.id === id)); } catch (error) { if (serial !== this.serial) return; this.rows = []; this.errorMessage = error.message || 'API request failed'; this.page.adminFinanceMetrics = null; } finally { if (serial === this.serial) this.loading = false; } },
    metrics(s) { return [{ label: '待確認充值', value: `${Number(s.pendingCount || 0)} 筆`, delta: `RM ${this.money(s.pendingAmount)}`, trend: Number(s.pendingCount) ? 'down' : 'up' }, { label: '已確認充值', value: `${Number(s.confirmedCount || 0)} 筆`, delta: '已增加預備金', trend: 'up' }, { label: '已退回申請', value: `${Number(s.rejectedCount || 0)} 筆`, delta: '保留退回原因', trend: Number(s.rejectedCount) ? 'down' : 'up' }, { label: '待同步 SQL', value: `${Number(s.pendingSyncCount || 0)} 筆`, delta: '會計同步狀態', trend: Number(s.pendingSyncCount) ? 'down' : 'up' }, { label: '本月確認充值', value: `RM ${this.money(s.confirmedMonthAmount)}`, delta: '本月實際入賬', trend: 'up' }]; },
    resetLoad() { this.pageNumber = 1; this.selectedIds = []; this.loadData(); }, goPage(n) { if (n >= 1 && n <= this.totalPages && n !== this.pageNumber) { this.pageNumber = n; this.loadData(); } }, selectRow(row) { this.selectedId = row.id; }, openDetails(row) { this.selectRow(row); this.$nextTick(() => this.$refs.detailDialog?.showModal()); }, closeDetails() { this.$refs.detailDialog?.close(); }, openProofFromDetails() { this.closeDetails(); this.$nextTick(this.openProof); }, openDecisionFromDetails(approved) { this.closeDetails(); this.$nextTick(() => this.openDecision(approved)); }, openReopenFromDetails() { this.closeDetails(); this.$nextTick(this.openReopen); }, documentUrl(row, type) { return row?.id ? getAdminFinanceDocumentUrl(row.id, type) : '#'; }, async batchDownload(type) { const ids = [...this.selectedIds]; if (!ids.length) { this.page.showToast('请先勾选需要下载的历史记录'); return; } this.batchBusy = true; try { const result = await downloadAdminFinanceDocuments(ids, type); const url = URL.createObjectURL(result.blob); const link = document.createElement('a'); link.href = url; link.download = result.filename; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); this.page.showToast(`已生成 ${ids.length} 份${type === 'invoice' ? '发票' : '收据'}`); } catch (error) { this.page.showToast(error.message || '批量下载失败'); } finally { this.batchBusy = false; } },
    toggleSelectablePage(event) { const ids = this.selectableRows.map(row => row.id); this.selectedIds = event.target.checked ? [...new Set([...this.selectedIds, ...ids])] : this.selectedIds.filter(id => !ids.includes(id)); },
    openDecision(approved) { this.approving = approved; this.decisionDate = todayIsoDate(); this.decisionNote = approved ? '充值资料与银行入账信息核对一致' : ''; this.actionError = ''; this.$refs.decisionDialog?.showModal(); }, closeDecision() { this.$refs.decisionDialog?.close(); },
    async submitDecision() { if (!this.decisionNote || (this.approving && !this.decisionDate)) { this.actionError = '請填寫審核資料'; return; } this.actionSaving = true; this.actionError = ''; try { if (this.approving) await confirmAdminFinanceReview(this.selectedRow.id, this.decisionDate, this.decisionNote); else await rejectAdminFinanceReview(this.selectedRow.id, this.decisionNote); this.closeDecision(); await this.loadData(); this.page.showToast(this.approving ? '預備金充值已確認並入賬' : '充值申請已退回'); } catch (error) { this.actionError = error.message || '充值審核失敗'; } finally { this.actionSaving = false; } },
    openRowReopen(row) { this.selectRow(row); this.$nextTick(this.openReopen); }, openReopen() { this.reopenNote = ''; this.actionError = ''; this.$refs.reopenDialog?.showModal(); }, closeReopen() { this.$refs.reopenDialog?.close(); }, async submitReopen() { if (!this.reopenNote) { this.actionError = this.$t('finance.reviewNoteRequired'); return; } this.actionSaving = true; this.actionError = ''; try { await reopenAdminFinanceReview(this.selectedRow.id, this.reopenNote); this.closeReopen(); await this.loadData(); this.page.showToast(this.$t('finance.reopenSuccess')); } catch (error) { this.actionError = error.message || this.$t('finance.reopenFailed'); } finally { this.actionSaving = false; } },
    openBatchReopen() { if (!this.selectedReopenIds.length) { this.page.showToast('请先勾选已确认充值'); return; } this.batchReopenNote = ''; this.actionError = ''; this.$refs.batchReopenDialog?.showModal(); }, closeBatchReopen() { this.$refs.batchReopenDialog?.close(); }, async submitBatchReopen() { if (!this.batchReopenNote) { this.actionError = '请填写退回原因'; return; } const ids = [...this.selectedReopenIds]; this.actionSaving = true; this.actionError = ''; try { await batchReopenAdminFinanceReviews(ids, this.batchReopenNote); this.closeBatchReopen(); this.selectedIds = []; await this.loadData(); this.page.showToast(`已批量退回 ${ids.length} 笔充值`); } catch (error) { this.actionError = error.message || '批量退回失败'; } finally { this.actionSaving = false; } },
    openBatch() { if (!this.selectedIds.length) this.selectedIds = this.pendingRows.map(row => row.id); if (!this.selectedIds.length) { this.page.showToast('当前列表没有可确认充值'); return; } this.batchDate = todayIsoDate(); this.actionError = ''; this.$refs.batchDialog?.showModal(); }, closeBatch() { this.$refs.batchDialog?.close(); }, async submitBatch() { if (!this.batchNote || !this.batchDate) return; this.actionSaving = true; this.actionError = ''; const count = this.selectedIds.length; try { await batchConfirmAdminFinanceReviews(this.selectedIds, this.batchDate, this.batchNote); this.closeBatch(); this.selectedIds = []; await this.loadData(); this.page.showToast(`已確認 ${count} 筆預備金充值`); } catch (error) { this.actionError = error.message || '批量確認失敗'; } finally { this.actionSaving = false; } },
    selectAndOpenProof(row) { this.selectRow(row); this.$nextTick(this.openProof); }, async openProof() { if (!this.selectedRow?.proofDocumentId) return; this.revokeProof(); this.proofLoading = true; this.proofError = ''; this.$refs.proofDialog?.showModal(); try { const result = await fetchAdminReserveProof(this.selectedRow.proofDocumentId); this.proofUrl = URL.createObjectURL(result.blob); } catch (error) { this.proofError = error.message || '憑證載入失敗'; } finally { this.proofLoading = false; } }, closeProof() { this.$refs.proofDialog?.close(); this.revokeProof(); }, revokeProof() { if (this.proofUrl) URL.revokeObjectURL(this.proofUrl); this.proofUrl = ''; }, async downloadProof() { try { const result = await fetchAdminReserveProof(this.selectedRow.proofDocumentId, true); const url = URL.createObjectURL(result.blob); const link = document.createElement('a'); link.href = url; link.download = this.selectedRow.proofName || `reserve-proof-${this.selectedRow.id}`; link.click(); URL.revokeObjectURL(url); } catch (error) { this.page.showToast(error.message || '憑證下載失敗'); } },
    statusParam(v) { return ({ '待確認': 'pending', '已確認': 'confirmed', '已退回': 'rejected', '待同步': 'sync_pending', '同步失敗': 'sync_failed' })[v] || ''; }, requestStatus() { if (this.viewMode === 'pending') return 'pending'; return this.statusParam(this.page.statusFilter) || 'history'; }, confirmationLabel(v) { return ({ pending: '待確認', confirmed: '已確認', rejected: '已退回' })[v] || '未知'; }, confirmationClass(v) { return v === 'confirmed' ? 'green' : v === 'rejected' ? 'red' : 'orange'; }, syncLabel(v) { return ({ not_synced: '未同步', pending: '待同步', synced: '已同步', failed: '同步失敗' })[v] || '未同步'; }, syncClass(v) { return v === 'synced' ? 'green' : v === 'failed' ? 'red' : 'orange'; }, paymentMethodLabel(v) { return ({ bank_transfer: '銀行轉賬', online_payment: '線上支付' })[v] || v || '—'; }, displayDate(v) { return formatDate(v); }, dateTime(v) { return formatDateTime(v); }, money(v) { return Number(v || 0).toLocaleString('en-MY', { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
  }
};
</script>

<style scoped>
.admin-reserve-finance-workspace { align-items: stretch; }.admin-reserve-finance-workspace .finance-review-panel { min-height: 590px; }.admin-reserve-finance-workspace td small { display: block; margin-top: 4px; color: #65788b; font-size: 11px; }.reserve-after { color: #15803d !important; }
</style>
<style scoped>
.finance-document-actions{display:grid;gap:4px;min-width:106px}.finance-document-actions a,.finance-document-button{display:inline-flex;align-items:center;justify-content:center;min-height:26px;padding:0 7px;border:1px solid #b7cfee;border-radius:6px;background:#f7fbff;color:#185a97;font-size:10px;text-decoration:none;white-space:nowrap}.finance-document-actions a:hover,.finance-document-button:hover{background:#eaf3ff;border-color:#6f9fda}
.reopen-link{min-height:26px;border:1px solid #efb3b3;border-radius:6px;background:#fff7f7;color:#b4232c;font-size:10px;font-weight:700}
.finance-list-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;flex-wrap:wrap}.history-batch-button{min-height:34px;padding:0 12px;border:1px solid #9bc9d0;border-radius:8px;background:#fff;color:#087078;font-size:12px;font-weight:700;cursor:pointer}.history-batch-button.danger{border-color:#efb6bb;background:#fff7f7;color:#bf2f3b}.history-batch-button:disabled{opacity:.45;cursor:not-allowed}
.finance-batch-overview{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.finance-batch-overview span{display:grid;gap:5px;padding:13px;border:1px solid #cfe4e5;border-radius:9px;background:#f1faf9;color:#66788b;font-size:12px}.finance-batch-overview b{color:#073b67;font-size:18px}
</style>
