<template>
  <div class="rent-collection-shell">
    <section class="content-grid admin-finance-workspace rent-collection-workspace">
      <div class="panel table-panel">
<div class="panel-head"><div><h2>{{ $t('legacy.t_710d4f0493f4') }}</h2><span>{{ totalRows }} {{ $t('legacy.t_7adaa1e9d2a2') }}</span></div><div class="rent-head-actions"><span v-if="selectedIds.length">{{ $t('legacy.t_743aaf951e5d') }} {{ selectedIds.length }} {{ $t('legacy.t_f4d0aeab9772') }}</span><button class="primary-btn rent-list-batch-trigger" :disabled="!rows.length" @click="openBatchConfirm">{{ selectedIds.length ? $t('ui.batchConfirmCount', { count: selectedIds.length }) : $t('legacy.t_7c18f2fec783') }}</button></div></div>
        <div v-if="errorMessage" class="admin-owner-state error"><strong>{{ $t('legacy.t_7f7fe4852d9d') }}</strong><span>{{ $lt(errorMessage) }}</span><button @click="loadData">{{ $t('legacy.t_0c9157b5bfac') }}</button></div>
        <div v-else class="table-wrap finance-review-table-wrap">
          <table>
            <thead><tr><th class="finance-check-cell"><input type="checkbox" :checked="allRowsSelected" :aria-label="$t('legacy.t_f7b7f7bcf37c')" @change="togglePageRows"></th><th>{{ $t('legacy.t_d7c14363a838') }}</th><th>{{ $t('legacy.t_114246450ff0') }}</th><th>{{ $t('legacy.t_a7ff541f4978') }}</th><th>{{ $t('legacy.t_fdeda5befee2') }}</th><th>{{ $t('legacy.t_eece4b5b3b99') }}</th><th>{{ $t('legacy.t_3060acf4dcc3') }}</th><th>{{ $t('legacy.t_11cb5e87977f') }}</th><th>{{ $t('legacy.t_2f0a2b15f977') }}</th><th>{{ $t('legacy.t_f3ea6d345e2a') }}</th></tr></thead>
            <tbody>
              <tr v-for="row in rows" :key="row.invoiceId" :class="{ selected: row.invoiceId === selectedId }" @click="selectedId = row.invoiceId">
<td class="finance-check-cell"><input v-model="selectedIds" type="checkbox" :value="row.invoiceId" :aria-label="$t('ui.selectLeaseAria', { leaseNo: row.leaseNo })" @click.stop></td>
                <td><strong>{{ row.leaseNo }}</strong><small>{{ row.tenantName }}</small></td>
                <td>{{ row.projectName }}<small>{{ row.unitNo }}</small></td>
                <td>{{ $lt(monthLabel(row.billingMonth)) }}</td><td>{{ $t('legacy.t_5e7b60c626a4') }} {{ money(row.amountDue) }}</td>
                <td class="money-green">{{ $t('legacy.t_5e7b60c626a4') }} {{ money(row.amountPaid) }}</td><td><b class="money-red">{{ $t('legacy.t_5e7b60c626a4') }} {{ money(row.outstandingAmount) }}</b></td>
                <td>{{ displayDate(row.dueDate) }}<small v-if="row.overdueDays">{{ $t('legacy.t_65a02a484e43') }} {{ row.overdueDays }} {{ $t('legacy.t_c3304d1e49e3') }}</small></td>
                <td><span class="tag" :class="statusClass(row.collectionStatus)">{{ $lt(statusLabel(row.collectionStatus)) }}</span></td>
                <td><button type="button" class="finance-detail-button" @click.stop="openDetails(row)">{{ $t('legacy.t_faea8c1db9cc') }}</button></td>
              </tr>
              <tr v-if="!loading && !rows.length"><td colspan="10" class="admin-owner-empty">{{ $t('legacy.t_9a82fd452d0e') }}</td></tr>
            </tbody>
          </table>
        </div>
        <div class="pager"><span>{{ $t('legacy.t_3b6ef811b85a') }} {{ totalRows }} {{ $t('legacy.t_d0bb9b2b8ea7') }}</span><div class="admin-building-pager"><button :disabled="pageNumber<=1" @click="goPage(pageNumber-1)">&lt;</button><button v-for="n in visiblePages" :key="n" :class="{active:n===pageNumber}" @click="goPage(n)">{{ n }}</button><button :disabled="pageNumber>=totalPages" @click="goPage(pageNumber+1)">&gt;</button><select v-model.number="pageSize"><option :value="10">{{ $t('legacy.t_fc6da0e815a1') }}</option><option :value="20">{{ $t('legacy.t_93d673672fa5') }}</option><option :value="50">{{ $t('legacy.t_529930b886d2') }}</option></select></div></div>
      </div>

      <dialog ref="detailDialog" class="modal finance-record-detail-dialog">
        <template v-if="selectedRow">
          <div class="modal-head"><div><h3>{{ $t('legacy.t_9e2303bdef68') }}</h3><small>{{ selectedRow.leaseNo }} · {{ $lt(monthLabel(selectedRow.billingMonth)) }}</small></div><button type="button" class="icon-close" @click="closeDetails">×</button></div>
          <div class="finance-record-detail-body">
          <div class="profile finance-review-profile"><div class="big-avatar">{{ $t('legacy.t_5d00753a306a') }}</div><div class="finance-review-profile-copy"><h3>{{ selectedRow.tenantName }}</h3><p>{{ selectedRow.projectName }} · {{ selectedRow.unitNo }}</p></div><span class="tag" :class="statusClass(selectedRow.collectionStatus)">{{ $lt(statusLabel(selectedRow.collectionStatus)) }}</span></div>
          <div class="detail-actions finance-review-actions"><button class="confirm" @click="openConfirmFromDetails">{{ $t('legacy.t_b52efc165fe3') }}</button><button @click="goToTenancyFromDetails">{{ $t('legacy.t_bcdce2d6efbe') }}</button><button v-if="selectedRow.latestProofDocumentId" @click="openProofFromDetails">{{ $t('legacy.t_df40a55c9e1c') }}</button></div>
          <div class="detail-section"><h4><span class="num">{{ $t('legacy.t_356a192b7913') }}</span>{{ $t('legacy.t_edeb2ce5b99b') }}</h4><div class="kv"><span>{{ $t('legacy.t_bd95f007d6d0') }}</span><b>{{ selectedRow.leaseNo }}</b></div><div class="kv"><span>{{ $t('legacy.t_a7ff541f4978') }}</span><b>{{ $lt(monthLabel(selectedRow.billingMonth)) }}</b></div><div class="kv"><span>{{ $t('legacy.t_fdeda5befee2') }}</span><b>{{ $t('legacy.t_5e7b60c626a4') }} {{ money(selectedRow.amountDue) }}</b></div><div class="kv"><span>{{ $t('legacy.t_eece4b5b3b99') }}</span><b class="money-green">{{ $t('legacy.t_5e7b60c626a4') }} {{ money(selectedRow.amountPaid) }}</b></div><div class="kv"><span>{{ $t('legacy.t_3060acf4dcc3') }}</span><b class="money-red">{{ $t('legacy.t_5e7b60c626a4') }} {{ money(selectedRow.outstandingAmount) }}</b></div><div class="progress"><i :style="{width:paymentProgress+'%'}"></i></div></div>
<div class="detail-section"><h4><span class="num">{{ $t('legacy.t_da4b9237bacc') }}</span>{{ $t('legacy.t_871046484e52') }}</h4><div class="kv"><span>{{ $t('legacy.t_11cb5e87977f') }}</span><b>{{ displayDate(selectedRow.dueDate) }}</b></div><div class="kv"><span>{{ $t('legacy.t_608d8eca243f') }}</span><b>{{ selectedRow.overdueDays ? $t('ui.overdueDaysCount', { count: selectedRow.overdueDays }) : $t('legacy.t_9f484e581ae0') }}</b></div><div class="kv"><span>{{ $t('legacy.t_27b064666adf') }}</span><b>{{ $t('legacy.t_5e7b60c626a4') }} {{ money(selectedRow.outstandingAmount) }}</b></div></div>
          <div class="detail-section"><h4><span class="num">{{ $t('legacy.t_77de68daecd8') }}</span>{{ $t('legacy.t_969d16f00bbf') }}</h4><div v-if="selectedRow.latestFinanceRecordId"><div class="kv"><span>{{ $t('legacy.t_32e88cf956f6') }}</span><b>{{ selectedRow.latestTransactionNo }}</b></div><div class="kv"><span>{{ $t('legacy.t_b35a920fa6f3') }}</span><b>{{ $t('legacy.t_5e7b60c626a4') }} {{ money(selectedRow.latestPaymentAmount) }}</b></div><div class="kv"><span>{{ $t('legacy.t_9afa4ce0531c') }}</span><b>{{ displayDate(selectedRow.latestPaymentDate) }}</b></div><div class="kv"><span>{{ $t('legacy.t_c6b9a8cfdb21') }}</span><b>{{ $lt(paymentMethodLabel(selectedRow.latestPaymentMethod)) }}</b></div><div class="kv"><span>{{ $t('legacy.t_41ee43593eb7') }}</span><b>{{ selectedRow.latestProofName || $t('legacy.t_4ca99b833c98') }}</b></div></div><p v-else class="empty-note">{{ $t('legacy.t_114205cf08dd') }}</p></div>
          </div>
        </template>
      </dialog>

      <dialog ref="confirmDialog" class="rent-confirm-dialog">
        <form @submit.prevent="submitConfirm">
          <header><div><h3>{{ $t('legacy.t_19c50942ffc4') }}</h3><p>{{ selectedRow?.tenantName }} · {{ selectedRow?.leaseNo }}</p></div><button type="button" @click="closeConfirm">×</button></header>
          <p v-if="actionError" ref="confirmError" class="rent-action-error" role="alert">{{ $lt(actionError) }}</p>
          <div class="rent-confirm-body">
            <div class="rent-amount-summary"><span>{{ $t('legacy.t_fdeda5befee2') }}<b>{{ $t('legacy.t_5e7b60c626a4') }} {{ money(selectedRow?.amountDue) }}</b></span><span>{{ $t('legacy.t_eece4b5b3b99') }}<b>{{ $t('legacy.t_5e7b60c626a4') }} {{ money(selectedRow?.amountPaid) }}</b></span><span>{{ $t('legacy.t_3060acf4dcc3') }}<b class="money-red">{{ $t('legacy.t_5e7b60c626a4') }} {{ money(selectedRow?.outstandingAmount) }}</b></span></div>
            <div class="rent-form-grid"><label>{{ $t('legacy.t_67aa62936fbc') }}<input v-model="form.amount" type="number" min="0.01" step="0.01" required><small v-if="advanceRentSummary" class="advance-rent-hint">{{ advanceRentSummary }}</small></label><label>{{ $t('legacy.t_9afa4ce0531c') }}<input v-model="form.receivedDate" type="date" :max="todayDate" required><small>{{ $t('legacy.t_ff18c74295eb') }}</small></label></div>
            <div class="rent-form-grid"><label>{{ $t('legacy.t_20f6e4a326f0') }}<input v-model="form.postingDate" type="date" required><small>{{ $t('legacy.t_b5433b84cff9') }}</small></label><span></span></div>
            <div class="rent-form-grid"><label>{{ $t('legacy.t_c6b9a8cfdb21') }}<select v-model="form.paymentMethod" required><option value="bank_transfer">{{ $t('legacy.t_789957b63e04') }}</option><option value="online_payment">{{ $t('legacy.t_6e249e45b116') }}</option><option value="cash">{{ $t('legacy.t_e3ca5905c270') }}</option><option value="cheque">{{ $t('legacy.t_61b73b219228') }}</option><option value="security_deposit">{{ $t('tenancy.securityDepositPayment') }}</option></select></label><label>{{ $t('legacy.t_d61f1eba334a') }}<input v-model.trim="form.payerName" maxlength="160" required></label></div>
            <label>{{ $t('legacy.t_91cdcd88db53') }}{{ $t('legacy.t_d33f62ae316e') }}<input v-model.trim="form.paymentReference" maxlength="120" :disabled="form.paymentMethod==='security_deposit'" :placeholder="form.paymentMethod==='security_deposit'?$t('legacy.t_9b64abbc22ab'):$t('legacy.t_aa71dae344a7')"></label>
            <label>{{ $t('legacy.t_f8aa34f40d01') }}<input ref="proofInput" type="file" accept="application/pdf,image/jpeg,image/png" @change="selectProof"><small>{{ proof?.name || $t('legacy.t_b35320f63845') }}</small></label>
            <label>{{ $t('legacy.t_0c819d5d6459') }}<textarea v-model.trim="form.note" maxlength="500" rows="3"></textarea></label>
            <label>{{ $t('legacy.t_abf3bed7e3d0') }}<textarea v-model.trim="form.allocationNote" maxlength="500" rows="3" :placeholder="$t('legacy.t_d214419cc5ae')"></textarea><small>{{ $t('legacy.t_bf69183401dc') }}</small></label>
            <label class="prepayment-choice"><input v-model="form.reuseAllocationNote" type="checkbox"><span>{{ $t('legacy.t_0fe389189c26') }}<small>{{ $t('legacy.t_2e0e1c61876c') }}</small></span></label>
            <div class="rent-confirm-notice"><b>{{ afterStatusText }}</b><span>{{ $t('legacy.t_5b9ebee75501') }}</span></div>
          </div>
          <menu><button type="button" @click="closeConfirm">{{ $t('legacy.t_4d0b4688c787') }}</button><button class="primary-btn" type="submit" :disabled="saving">{{ saving?$t('legacy.t_6a9b39fafbcc'):$t('legacy.t_6b8683619d6e') }}</button></menu>
        </form>
      </dialog>

      <dialog ref="batchDialog" class="rent-confirm-dialog rent-batch-dialog">
        <form @submit.prevent="submitBatchConfirm">
          <header><div><h3>{{ $t('legacy.t_0f5e0a11b8ca') }}</h3><p>{{ $t('legacy.t_cb861770ce4d') }} {{ batchRows.length }} {{ $t('legacy.t_eea75119c622') }} {{ money(batchOutstanding) }}</p></div><button type="button" @click="closeBatchConfirm">×</button></header>
          <p v-if="batchError" class="rent-action-error" role="alert">{{ $lt(batchError) }}</p>
          <div class="rent-confirm-body">
            <div class="batch-rent-summary"><span>{{ $t('legacy.t_4a96dc3579fb') }}<b>{{ batchRows.length }} {{ $t('legacy.t_f4d0aeab9772') }}</b></span><span>{{ $t('legacy.t_13c369913cee') }}<b>{{ $t('legacy.t_5e7b60c626a4') }} {{ money(batchOutstanding) }}</b></span><span>{{ $t('legacy.t_416d5bde856f') }}<b>{{ $lt(paymentMethodLabel(batchForm.paymentMethod)) }}</b></span></div>
            <div class="batch-rent-list"><div v-for="row in batchRows" :key="row.invoiceId"><span><b>{{ row.tenantName }}</b><small>{{ row.projectName }} · {{ row.unitNo }} · {{ $lt(monthLabel(row.billingMonth)) }}</small></span><strong>{{ $t('legacy.t_5e7b60c626a4') }} {{ money(row.outstandingAmount) }}</strong></div></div>
            <div class="rent-confirm-notice"><b>{{ $t('legacy.t_d58d5c2bd372') }}</b><span>{{ $t('legacy.t_aca90b23f805') }}</span></div>
            <div class="rent-form-grid"><label>{{ $t('legacy.t_9afa4ce0531c') }}<input v-model="batchForm.receivedDate" type="date" :max="todayDate" required><small>{{ $t('legacy.t_5d33112e3325') }}</small></label><label>{{ $t('legacy.t_20f6e4a326f0') }}<input v-model="batchForm.postingDate" type="date" required><small>{{ $t('legacy.t_242842dff542') }}</small></label></div>
            <label>{{ $t('legacy.t_c6b9a8cfdb21') }}<select v-model="batchForm.paymentMethod" required><option value="bank_transfer">{{ $t('legacy.t_afba6a4b6fae') }}</option><option value="online_payment">{{ $t('legacy.t_d1af0d2119b1') }}</option><option value="cash">{{ $t('legacy.t_6548450b8d16') }}</option><option value="cheque">{{ $t('legacy.t_61b73b219228') }}</option><option value="security_deposit">{{ $t('legacy.t_7c41327d495e') }}</option></select></label>
            <label>{{ $t('legacy.t_f374baba79e1') }}<input v-model.trim="batchForm.paymentReference" maxlength="120" :disabled="batchForm.paymentMethod==='security_deposit'" :placeholder="batchForm.paymentMethod==='security_deposit'?$t('legacy.t_9a27f289a90d'):$t('legacy.t_46c0d9d503ad')"></label>
            <label>{{ $t('legacy.t_9fc15be169de') }}<textarea v-model.trim="batchForm.note" maxlength="500" rows="3" required></textarea></label>
            <label>{{ $t('legacy.t_abf3bed7e3d0') }}<textarea v-model.trim="batchForm.allocationNote" maxlength="500" rows="3" :placeholder="$t('legacy.t_c35497e30389')"></textarea></label>
            <label class="prepayment-choice"><input v-model="batchForm.reuseAllocationNote" type="checkbox"><span>{{ $t('legacy.t_0fe389189c26') }}<small>{{ $t('legacy.t_e6d8f7db3fd5') }}</small></span></label>
          </div>
          <menu><button type="button" @click="closeBatchConfirm">{{ $t('legacy.t_4d0b4688c787') }}</button><button class="primary-btn" type="submit" :disabled="batchSaving || !batchRows.length">{{ batchSaving ? $t('legacy.t_0cfdfc117938') : $t('ui.batchConfirmCount', { count: batchRows.length }) }}</button></menu>
        </form>
      </dialog>

      <dialog ref="proofDialog" class="modal admin-finance-proof-dialog"><div class="modal-head"><div><h3>{{ $t('legacy.t_bf3848894d3f') }}</h3><small>{{ selectedRow?.latestProofName }}</small></div><button class="icon-close" @click="closeProof">×</button></div><div class="finance-proof-viewer"><div v-if="proofLoading" class="admin-owner-state">{{ $t('legacy.t_6ce3778a43cd') }}</div><img v-else-if="proofUrl&&selectedRow?.latestProofMimeType?.startsWith('image/')" :src="proofUrl"><iframe v-else-if="proofUrl&&selectedRow?.latestProofMimeType==='application/pdf'" :src="proofUrl"></iframe><div v-else class="admin-owner-state">{{ proofError||$t('legacy.t_7db08b273aa4') }}</div></div><menu><button @click="closeProof">{{ $t('legacy.t_ddc05404b0d6') }}</button></menu></dialog>
    </section>
  </div>
</template>

<script>
import { batchConfirmAdminRentCollections, confirmAdminRentCollection, fetchAdminRentCollectionProjects, fetchAdminRentCollections, fetchAdminRentProof } from '../services/propertyApi';
import { formatDate } from '../utils/dateFormat';
const localToday=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10);};
export default {
  inject:['page'],
  data(){return{rows:[],selectedId:null,selectedIds:[],batchRows:[],pageNumber:1,pageSize:5,totalRows:0,totalPages:1,loading:false,errorMessage:'',requestSerial:0,todayDate:localToday(),form:{amount:'',receivedDate:localToday(),postingDate:localToday(),paymentMethod:'bank_transfer',payerName:'',paymentReference:'',note:'',allocationNote:'',reuseAllocationNote:true},batchForm:{receivedDate:localToday(),postingDate:localToday(),paymentMethod:'bank_transfer',paymentReference:'',note:'批量核对租金收款无误',allocationNote:'',reuseAllocationNote:true},proof:null,saving:false,batchSaving:false,actionError:'',batchError:'',proofLoading:false,proofUrl:'',proofError:''};},
  computed:{selectedRow(){return this.rows.find(r=>r.invoiceId===this.selectedId)||this.rows[0]||null;},selectedRows(){return this.rows.filter(row=>this.selectedIds.includes(row.invoiceId));},selectedOutstanding(){return this.selectedRows.reduce((sum,row)=>sum+Number(row.outstandingAmount||0),0);},batchOutstanding(){return this.batchRows.reduce((sum,row)=>sum+Number(row.outstandingAmount||0),0);},allRowsSelected(){return this.rows.length>0&&this.rows.every(row=>this.selectedIds.includes(row.invoiceId));},visiblePages(){const start=Math.max(1,Math.min(this.pageNumber-2,this.totalPages-4));return Array.from({length:Math.min(5,this.totalPages)},(_,i)=>start+i);},paymentProgress(){return !Number(this.selectedRow?.amountDue)?0:Math.min(100,Math.round(Number(this.selectedRow.amountPaid||0)/Number(this.selectedRow.amountDue)*100));},collectionNonce(){return this.page.adminRentCollectionNonce;},batchNonce(){return this.page.adminFinanceBatchNonce;},targetInvoiceId(){return this.page.adminFinanceTargetInvoiceId;},advanceRentPlan(){const row=this.selectedRow,amount=Number(this.form.amount||0);if(!row||!Number.isFinite(amount)||amount<=0)return null;let remaining=amount,month=this.monthStart(row.billingMonth),lastMonth=this.monthStart(row.leaseEndDate),months=0,last=null;while(remaining>0.005&&month&&lastMonth&&month<=lastMonth){const due=month===this.monthStart(row.billingMonth)?Number(row.outstandingAmount||0):this.monthlyInvoiceAmount(row,month);if(due>0){const paid=Math.min(remaining,due);months+=1;last={paid,due,remaining:Math.max(due-paid,0)};remaining-=paid;}month=this.addMonth(month);}return{months,last,exceeds:remaining>0.005};},advanceRentSummary(){const plan=this.advanceRentPlan;if(!plan)return '';if(plan.exceeds)return this.$t('tenancy.advanceRentExceedsLease');let text=this.$t('tenancy.advanceRentMonths',{months:plan.months});if(plan.last?.remaining>0.005)text+=` ${this.$t('tenancy.advanceRentPartial',{amount:this.money(plan.last.paid),due:this.money(plan.last.due),remaining:this.money(plan.last.remaining)})}`;return text;},afterStatusText(){const remaining=Number(this.selectedRow?.outstandingAmount||0)-Number(this.form.amount||0);if(this.advanceRentPlan?.exceeds)return this.$t('tenancy.advanceRentExceedsLease');return remaining<=0?'本期租金將標記為已收齊':`入帳後仍有 RM ${this.money(Math.max(remaining,0))} 待收`; }},
  watch:{'page.moduleSearch'(){this.resetLoad();},'page.globalSearch'(){this.resetLoad();},'page.projectFilter'(){this.resetLoad();},'page.statusFilter'(){this.resetLoad();},'page.dateStart'(){this.resetLoad();},'page.dateEnd'(){this.resetLoad();},pageSize(){this.pageNumber=1;this.loadData();},targetInvoiceId(v,p){if(v&&v!==p){this.pageNumber=1;this.loadData();}},collectionNonce(v,p){if(v>p)this.$nextTick(this.openConfirm);},batchNonce(v,p){if(v>p)this.$nextTick(this.openBatchConfirm);},rows:{deep:true,handler(v){if(!v.some(r=>r.invoiceId===this.selectedId))this.selectedId=v[0]?.invoiceId||null;}}},
  mounted(){this.loadData();},beforeUnmount(){this.revokeProof();},
  methods:{
    displayDate(value){return formatDate(value);},
    async loadData(){
      const serial=++this.requestSerial,preferred=this.selectedId,targetInvoiceId=Number(this.targetInvoiceId)||null;
      this.loading=true;this.errorMessage='';
      const filters=targetInvoiceId
        ? {page:1,pageSize:this.pageSize,invoiceId:this.targetInvoiceId}
        : {page:this.pageNumber,pageSize:this.pageSize,keyword:this.page.globalSearch||this.page.moduleSearch||'',projectName:String(this.page.projectFilter||'').includes('全部')?'':this.page.projectFilter,status:this.statusParam(this.page.statusFilter),startDate:this.page.dateStart,endDate:this.page.dateEnd};
      try{
        const [response,projects]=await Promise.all([fetchAdminRentCollections(filters),fetchAdminRentCollectionProjects()]);
        if(serial!==this.requestSerial)return;
        this.rows=response.rows||[];this.totalRows=response.page?.totalRows||0;this.totalPages=response.page?.totalPages||1;this.pageNumber=response.page?.page||1;
        const targetRow=targetInvoiceId?this.rows.find(row=>Number(row.invoiceId)===targetInvoiceId):null;
        if(targetRow)this.selectedId=targetRow.invoiceId;
        else this.selectedId=this.rows.some(r=>r.invoiceId===preferred)?preferred:this.rows[0]?.invoiceId||null;
        this.selectedIds=this.selectedIds.filter(id=>this.rows.some(row=>row.invoiceId===id));this.page.adminFinanceProjects=projects||[];this.page.adminFinanceMetrics=this.metrics(response.summary||{});
        if(targetRow){this.page.adminFinanceTargetInvoiceId=null;this.$nextTick(this.openConfirm);}
      }catch(e){if(serial!==this.requestSerial)return;this.rows=[];this.selectedIds=[];this.errorMessage=e.message||'API request failed';this.page.adminFinanceMetrics=null;}
      finally{if(serial===this.requestSerial)this.loading=false;}
    },
    metrics(s){return[{label:'待收租金帳單',value:`${Number(s.outstandingCount||0)} 筆`,delta:`RM ${this.money(s.outstandingAmount)}`,trend:Number(s.outstandingCount)?'down':'up'},{label:'完全未支付',value:`${Number(s.unpaidCount||0)} 筆`,delta:'尚未收到任何款項',trend:Number(s.unpaidCount)?'down':'up'},{label:'部分支付',value:`${Number(s.partialCount||0)} 筆`,delta:'仍需繼續收款',trend:Number(s.partialCount)?'down':'up'},{label:'逾期帳單',value:`${Number(s.overdueCount||0)} 筆`,delta:'需要跟進',trend:Number(s.overdueCount)?'down':'up'},{label:'本月已收租金',value:`RM ${this.money(s.monthReceived)}`,delta:'已確認入帳',trend:'up'}];},
    resetLoad(){this.pageNumber=1;this.selectedIds=[];this.loadData();},goPage(n){if(n>=1&&n<=this.totalPages&&n!==this.pageNumber){this.pageNumber=n;this.selectedIds=[];this.loadData();}},selectAndConfirm(row){this.selectedId=row.invoiceId;this.$nextTick(this.openConfirm);},openDetails(row){this.selectedId=row.invoiceId;this.$nextTick(()=>this.$refs.detailDialog?.showModal());},closeDetails(){this.$refs.detailDialog?.close();},openConfirmFromDetails(){this.closeDetails();this.$nextTick(this.openConfirm);},goToTenancyFromDetails(){this.closeDetails();this.goToTenancy();},openProofFromDetails(){this.closeDetails();this.$nextTick(this.openProof);},togglePageRows(event){const ids=this.rows.map(row=>row.invoiceId);this.selectedIds=event.target.checked?[...new Set([...this.selectedIds,...ids])]:this.selectedIds.filter(id=>!ids.includes(id));},
    openConfirm(){if(!this.selectedRow)return;this.form={amount:Number(this.selectedRow.outstandingAmount||0).toFixed(2),receivedDate:localToday(),postingDate:this.monthStart(this.selectedRow.billingMonth)||localToday(),paymentMethod:'bank_transfer',payerName:this.selectedRow.tenantName||'',paymentReference:'',note:'',allocationNote:'',reuseAllocationNote:true};this.proof=null;this.actionError='';if(this.$refs.proofInput)this.$refs.proofInput.value='';this.$refs.confirmDialog?.showModal();},closeConfirm(){if(!this.saving)this.$refs.confirmDialog?.close();},showConfirmError(message){this.actionError=message;},selectProof(e){const f=e.target.files?.[0]||null;if(f&&(!['application/pdf','image/jpeg','image/png'].includes(f.type)||f.size>10*1024*1024)){this.showConfirmError('只支援 10MB 以內的 PDF、JPG 或 PNG 憑證');e.target.value='';this.proof=null;return;}this.proof=f;},
    async submitConfirm(){const amount=Number(this.form.amount);if(!Number.isFinite(amount)||amount<=0){this.showConfirmError('本次實收金額必須大於 0。');return;}if(this.form.paymentMethod==='security_deposit'&&amount>Number(this.selectedRow?.outstandingAmount||0)){this.showConfirmError(this.$t('tenancy.securityDepositCurrentOnly'));return;}if(this.advanceRentPlan?.exceeds){this.showConfirmError(this.$t('tenancy.advanceRentExceedsLease'));return;}this.saving=true;this.actionError='';try{const result=await confirmAdminRentCollection(this.selectedRow.invoiceId,{...this.form,paymentReference:this.form.paymentMethod==='security_deposit'?null:(this.form.paymentReference||null),amount:amount.toFixed(2)},this.proof);this.$refs.confirmDialog?.close();await this.loadData();this.page.showToast(this.$ltf`租金已確認入帳：${result.referenceNo}，收據已產生`);}catch(e){this.showConfirmError(e.message||'租金確認失敗');}finally{this.saving=false;}},
    openBatchConfirm(){const selected=this.selectedRows.filter(row=>Number(row.outstandingAmount||0)>0);this.batchRows=(selected.length?selected:this.rows.filter(row=>Number(row.outstandingAmount||0)>0)).map(row=>({...row}));if(!this.batchRows.length){this.page.showToast('当前列表没有可确认的租金账单');return;}const postingDate=this.monthStart(this.batchRows[0]?.billingMonth)||localToday();this.batchForm={receivedDate:localToday(),postingDate,paymentMethod:'bank_transfer',paymentReference:'',note:'批量核对租金收款无误',allocationNote:'',reuseAllocationNote:true};this.batchError='';this.$refs.batchDialog?.showModal();},closeBatchConfirm(){if(!this.batchSaving)this.$refs.batchDialog?.close();},async submitBatchConfirm(){const invoiceIds=this.batchRows.map(row=>row.invoiceId);if(!invoiceIds.length)return;this.batchSaving=true;this.batchError='';const count=invoiceIds.length;try{await batchConfirmAdminRentCollections({invoiceIds,receivedDate:this.batchForm.receivedDate,postingDate:this.batchForm.postingDate,paymentMethod:this.batchForm.paymentMethod,paymentReference:this.batchForm.paymentMethod==='security_deposit'?null:(this.batchForm.paymentReference||null),note:this.batchForm.note,allocationNote:this.batchForm.allocationNote||null,reuseAllocationNote:this.batchForm.reuseAllocationNote});this.$refs.batchDialog?.close();this.selectedIds=[];this.batchRows=[];await this.loadData();this.page.showToast(this.$ltf`已批量确认 ${count} 笔租金收款`);}catch(e){this.batchError=e.message||'批量确认租金失败';}finally{this.batchSaving=false;}},
    async openProof(){if(!this.selectedRow?.latestProofDocumentId)return;this.revokeProof();this.proofLoading=true;this.proofError='';this.$refs.proofDialog?.showModal();try{const r=await fetchAdminRentProof(this.selectedRow.latestProofDocumentId);this.proofUrl=URL.createObjectURL(r.blob);}catch(e){this.proofError=e.message||'憑證載入失敗';}finally{this.proofLoading=false;}},closeProof(){this.$refs.proofDialog?.close();this.revokeProof();},revokeProof(){if(this.proofUrl)URL.revokeObjectURL(this.proofUrl);this.proofUrl='';},goToTenancy(){const k=this.selectedRow?.tenantName||'';this.page.selectModule('adminTenants');this.$nextTick(()=>{this.page.globalSearch=k;});},monthStart(v){return v?String(v).slice(0,10):'';},addMonth(v){const [year,month]=v.split('-').map(Number);return `${month===12?year+1:year}-${String(month===12?1:month+1).padStart(2,'0')}-01`;},monthlyInvoiceAmount(row,month){const monthlyRent=Number(row.monthlyRent||0);if(row.rentCalculationMethod!=='daily_prorated')return monthlyRent;const start=Math.max(new Date(`${row.leaseStartDate}T00:00:00Z`).getTime(),new Date(`${month}T00:00:00Z`).getTime());const monthEnd=new Date(`${month.slice(0,7)}-01T00:00:00Z`);monthEnd.setUTCMonth(monthEnd.getUTCMonth()+1);const end=Math.min(new Date(`${row.leaseEndDate}T00:00:00Z`).getTime(),monthEnd.getTime()-86400000);if(start>end)return 0;const days=Math.round((end-start)/86400000)+1;const daysInMonth=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),0)).getUTCDate();return Math.max(Number((monthlyRent*days/daysInMonth).toFixed(2)),monthlyRent>0?0.01:0);},statusParam(v){return({'未支付':'unpaid','部分支付':'partial','已逾期':'overdue'})[v]||'';},statusLabel(v){return({unpaid:'未支付',partial:'部分支付',overdue:'已逾期'})[v]||v;},statusClass(v){return v==='partial'?'orange':v==='overdue'?'red':'gray';},paymentMethodLabel(v){return({bank_transfer:'銀行轉帳',online_payment:'線上支付',cash:'現金',cheque:'支票',security_deposit:this.$t('tenancy.securityDepositPayment')})[v]||v||'—';},monthLabel(v){return v?String(v).slice(0,7):'—';},money(v){return Number(v||0).toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2});}
  }
};
</script>

<style scoped>
.panel-head{display:flex;align-items:center;justify-content:space-between}.panel-head h2{margin:0 0 4px}.panel-head span,td small{display:block;color:#6b7d91;font-size:11px;margin-top:4px}.confirm-rent-button{border:0;border-radius:6px;background:#0b376c;color:#fff;padding:6px 10px;white-space:nowrap}.empty-note{color:#718096;text-align:center}.rent-confirm-dialog{width:min(650px,calc(100vw - 30px));padding:0;border:0;border-radius:12px;box-shadow:0 25px 80px #06172c55}.rent-confirm-dialog::backdrop{background:#09182a80}.rent-confirm-dialog header{display:flex;justify-content:space-between;gap:16px;padding:19px 22px;border-bottom:1px solid #e1e8f0}.rent-confirm-dialog h3{margin:0 0 4px}.rent-confirm-dialog header p{margin:0;color:#64748b}.rent-confirm-dialog header button{border:0;background:none;font-size:26px}.rent-confirm-body{display:grid;gap:15px;padding:20px 22px;max-height:68vh;overflow:auto}.rent-amount-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.rent-amount-summary span{display:grid;gap:4px;padding:10px;border-radius:7px;background:#f5f8fb;color:#617287;font-size:12px}.rent-amount-summary b{color:#122943;font-size:15px}.rent-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.rent-confirm-body label{display:grid;gap:6px;color:#293e56;font-size:13px;font-weight:600}.rent-confirm-body input,.rent-confirm-body select,.rent-confirm-body textarea{box-sizing:border-box;width:100%;border:1px solid #cdd8e4;border-radius:7px;padding:10px 11px;background:#fff;font:inherit}.rent-confirm-body textarea{resize:vertical}.rent-confirm-body small{color:#718096;font-weight:400}.rent-confirm-notice{display:grid;gap:4px;padding:11px 13px;border:1px solid #efd28d;border-radius:8px;background:#fff9ea;color:#7a5908;font-size:12px}.prepayment-choice{grid-template-columns:auto 1fr;align-items:start;padding:12px;border:1px solid #8cc8c0;border-radius:8px;background:#f1fbf9;color:#174e51}.prepayment-choice input{width:auto;margin:3px 0 0}.prepayment-choice span{display:grid;gap:3px}.prepayment-choice small{color:#477878}.rent-action-error{margin:12px 22px 0;padding:10px 12px;border:1px solid #f1b8bd;border-radius:8px;background:#fff1f2;color:#c92f3b;font-size:13px;font-weight:700}.rent-confirm-dialog menu{display:flex;justify-content:flex-end;gap:9px;margin:0;padding:14px 22px;background:#f7f9fb}.rent-confirm-dialog menu button{border:1px solid #ced8e4;border-radius:7px;background:#fff;padding:9px 18px}.rent-confirm-dialog menu .primary-btn{background:#d89200;border-color:#d89200;color:#fff}@media(max-width:600px){.rent-form-grid,.rent-amount-summary{grid-template-columns:1fr}}
.rent-head-actions{display:flex;align-items:center;gap:8px}.rent-head-actions>span{color:#64748b;font-size:12px}.batch-rent-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.batch-rent-summary span{display:grid;gap:5px;padding:12px;border-radius:8px;background:#eef8f7;color:#617287;font-size:12px}.batch-rent-summary b{color:#063d62;font-size:16px}.finance-check-cell{width:38px;text-align:center}.finance-check-cell input{width:16px;height:16px;accent-color:#078b8d}@media(max-width:760px){.rent-head-actions{flex-wrap:wrap;justify-content:flex-end}.batch-rent-summary{grid-template-columns:1fr}}
.batch-rent-list{display:grid;max-height:210px;overflow:auto;border:1px solid #dce7ee;border-radius:9px}.batch-rent-list>div{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:10px 12px;border-bottom:1px solid #edf2f6}.batch-rent-list>div:last-child{border-bottom:0}.batch-rent-list span{display:grid;gap:3px}.batch-rent-list small{color:#6b7d91;font-weight:400}.batch-rent-list strong{white-space:nowrap;color:#063d62}
.rent-collection-shell{padding:10px 4px 30px}.rent-collection-workspace{grid-template-columns:minmax(0,1fr)!important;align-items:start;gap:18px!important;padding:0 28px!important}.rent-collection-workspace>.panel{border-radius:14px;box-shadow:0 8px 24px rgba(25,63,82,.06)}.rent-collection-workspace .finance-review-profile{padding:0 0 18px}.rent-collection-workspace .finance-review-actions{gap:10px;padding:16px 0}.rent-collection-workspace .detail-section{padding:18px 0}.rent-collection-workspace .detail-section:last-child{padding-bottom:4px}@media(max-width:600px){.rent-collection-shell{padding-top:4px}.rent-collection-workspace{padding:0 12px!important;gap:16px!important}}
</style>
<style scoped>
.advance-rent-hint{color:#8b6200!important;line-height:1.5}
</style>
