<template>
  <section class="content-grid admin-tenancy-workspace">
    <div class="panel table-panel tenancy-list-panel">
      <div class="panel-head"><div><h2>租客與租金列表</h2><span>{{ totalRows }} records</span></div><span v-if="loading" class="tenancy-loading">正在載入…</span></div>
      <div v-if="errorMessage" class="admin-owner-state error"><strong>租務資料載入失敗</strong><span>{{ errorMessage }}</span><button @click="loadData">重新載入</button></div>
      <div v-else class="table-wrap tenancy-table-wrap">
        <table>
          <thead><tr><th>租客</th><th>建案／單位</th><th>租約</th><th>本期應收</th><th>已收／未收</th><th>到期日</th><th>租金狀態</th><th>操作</th></tr></thead>
          <tbody>
            <tr v-for="row in rows" :key="`${row.tenantId}-${row.leaseId || 0}`" :class="{ selected: row.tenantId === selectedRow?.tenantId }" @click="selectedId = row.tenantId">
              <td><strong>{{ row.tenantName }}</strong><small>{{ row.phone || row.email || '未設定聯絡資料' }}</small></td>
              <td>{{ row.projectName || '尚未建立租約' }}<small>{{ row.unitNo || '—' }}</small></td>
              <td>{{ row.leaseNo || '—' }}<small v-if="row.leaseStart">{{ row.leaseStart }} ~ {{ row.leaseEnd }}</small></td>
              <td><b>{{ money(row.amountDue) }}</b></td>
              <td><span class="tenancy-paid">{{ money(row.amountPaid) }}</span><small class="tenancy-unpaid">未收 {{ money(row.amountUnpaid) }}</small></td>
              <td>{{ row.dueDate || '—' }}</td>
              <td><span class="tag" :class="rentClass(row.rentStatus)">{{ rentLabel(row.rentStatus) }}</span></td>
              <td><button class="row-actions" title="查看詳情" @click.stop="selectedId = row.tenantId">…</button></td>
            </tr>
            <tr v-if="!loading && !rows.length"><td colspan="8" class="admin-owner-empty">目前沒有符合條件的租務資料</td></tr>
          </tbody>
        </table>
      </div>
      <div class="pager"><span>共 {{ totalRows }} records</span><div class="admin-building-pager"><button :disabled="pageNumber <= 1" @click="goPage(pageNumber - 1)">&lt;</button><button v-for="n in visiblePages" :key="n" :class="{ active: n === pageNumber }" @click="goPage(n)">{{ n }}</button><button :disabled="pageNumber >= totalPages" @click="goPage(pageNumber + 1)">&gt;</button><select v-model.number="pageSize"><option :value="10">10 條/頁</option><option :value="20">20 條/頁</option><option :value="50">50 條/頁</option></select></div></div>
    </div>

    <aside class="panel detail-panel tenancy-detail-panel">
      <div v-if="selectedRow" class="detail-card">
        <div class="profile tenancy-profile"><div class="big-avatar">{{ initials(selectedRow.tenantName) }}</div><div><h3>{{ selectedRow.tenantName }}</h3><p>{{ selectedRow.projectName || '尚未建立租約' }} · {{ selectedRow.unitNo || '—' }}</p></div><span class="tag" :class="rentClass(selectedRow.rentStatus)">{{ rentLabel(selectedRow.rentStatus) }}</span></div>
        <div class="detail-actions tenancy-actions">
          <button :disabled="selectedRow.leaseStatus !== 'active'" @click="openEditLease">修改租約</button>
          <button :disabled="selectedRow.leaseStatus !== 'active'" @click="openTransferLease">轉租</button>
          <button v-if="selectedRow.contractDocumentId" :disabled="contractBusy" @click="viewContract">查看租約</button>
          <button v-if="selectedRow.contractDocumentId" :disabled="contractBusy" @click="downloadContract">下載租約</button>
          <button :disabled="!selectedRow.leaseId || contractBusy" @click="chooseContract">
            {{ contractBusy ? '處理中…' : selectedRow.contractDocumentId ? '更換租約' : '上傳租約' }}
          </button>
          <input ref="contractInput" type="file" accept="application/pdf,image/jpeg,image/png" style="display:none" @change="uploadSelectedContract">
          <button :disabled="!selectedRow.invoiceId || !Number(selectedRow.amountUnpaid)" @click="sendReminder">發送通知</button>
        </div>
        <div class="detail-section"><h4><span class="num">1</span>租客資料</h4><div class="kv"><span>身份證件</span><b>{{ selectedRow.identityNo || '—' }}</b></div><div class="kv"><span>電話</span><b>{{ selectedRow.phone || '—' }}</b></div><div class="kv"><span>Email</span><b>{{ selectedRow.email || '—' }}</b></div><div class="kv"><span>狀態</span><b>{{ selectedRow.tenantStatus === 'active' ? '啟用' : '停用' }}</b></div></div>
        <div class="detail-section"><h4><span class="num">2</span>租約資料</h4><div class="kv"><span>租約編號</span><b>{{ selectedRow.leaseNo || '—' }}</b></div><div class="kv"><span>租期</span><b>{{ selectedRow.leaseStart ? `${selectedRow.leaseStart} ~ ${selectedRow.leaseEnd}` : '—' }}</b></div><div class="kv"><span>月租</span><b>{{ money(selectedRow.monthlyRent) }}</b></div><div class="kv"><span>押金</span><b>{{ money(selectedRow.depositAmount) }}</b></div><div class="kv"><span>每月繳租日</span><b>{{ selectedRow.paymentDay ? `${selectedRow.paymentDay} 日` : '—' }}</b></div><div class="kv"><span>租約文件</span><b>{{ selectedRow.contractDocumentName || '尚未上傳' }}</b></div></div>
        <div class="detail-section"><h4><span class="num">3</span>本期租金</h4><div class="kv"><span>帳單月份</span><b>{{ selectedRow.billingMonth || '—' }}</b></div><div class="kv"><span>應收</span><b>{{ money(selectedRow.amountDue) }}</b></div><div class="kv"><span>已入帳金額</span><b class="tenancy-paid">{{ money(selectedRow.amountPaid) }}</b></div><div class="kv"><span>未收</span><b class="money-red">{{ money(selectedRow.amountUnpaid) }}</b></div><div class="progress"><i :style="{ width: rentProgress + '%' }"></i></div></div>
      </div>
      <div v-else class="admin-owner-empty">目前沒有可查看的租客</div>
    </aside>

    <dialog ref="tenantDialog" class="modal admin-tenancy-dialog"><form method="dialog" @submit.prevent="submitTenant"><div class="modal-head"><div><h3>新增租客</h3><small>建立租客基本資料；租約可在下一步建立</small></div><button type="button" class="icon-close" @click="closeDialog('tenantDialog')">×</button></div><div class="form-grid tenancy-form"><label>租客姓名<input v-model.trim="tenantForm.fullName" required maxlength="160"></label><label>身份證件<input v-model.trim="tenantForm.identityNo" maxlength="120"></label><label>電話<input v-model.trim="tenantForm.phone" maxlength="40"></label><label>Email<input v-model.trim="tenantForm.email" type="email" maxlength="190"></label><label>狀態<select v-model="tenantForm.status"><option value="active">啟用</option><option value="inactive">停用</option></select></label><p v-if="actionError" class="admin-property-error">{{ actionError }}</p></div><menu><button type="button" @click="closeDialog('tenantDialog')">取消</button><button class="primary-btn" :disabled="saving">{{ saving ? '建立中…' : '建立租客' }}</button></menu></form></dialog>

    <dialog ref="leaseDialog" class="modal admin-tenancy-dialog"><form method="dialog" @submit.prevent="submitLease"><div class="modal-head"><div><h3>新增租約</h3><small>只可選擇目前沒有有效租約的已交房單位</small></div><button type="button" class="icon-close" @click="closeDialog('leaseDialog')">×</button></div><div class="form-grid tenancy-form"><label>租客<select v-model.number="leaseForm.tenantId" required><option :value="null" disabled>選擇租客</option><option v-for="t in options.tenants" :key="t.id" :value="t.id">{{ t.name }}</option></select></label><label>出租單位<select v-model.number="leaseForm.unitId" required><option :value="null" disabled>選擇單位</option><option v-for="u in options.units" :key="u.id" :value="u.id">{{ u.projectName }} · {{ u.unitNo }}</option></select></label><label>開始日期<input v-model="leaseForm.startDate" type="date" required></label><label>結束日期<input v-model="leaseForm.endDate" type="date" required></label><label>月租（RM）<input v-model.number="leaseForm.monthlyRent" type="number" min="0.01" step="0.01" required></label><label>押金（RM）<input v-model.number="leaseForm.depositAmount" type="number" min="0" step="0.01" required></label><label>每月繳租日<input v-model.number="leaseForm.paymentDay" type="number" min="1" max="31" required></label><label class="tenancy-contract-field">租約文件（選填）<input type="file" accept="application/pdf,image/jpeg,image/png" @change="selectNewLeaseContract"><small>PDF、JPG 或 PNG，最大 10MB</small></label><p v-if="!options.units.length" class="admin-property-error">目前沒有可出租的已交房單位</p><p v-if="actionError" class="admin-property-error">{{ actionError }}</p></div><menu><button type="button" @click="closeDialog('leaseDialog')">取消</button><button class="primary-btn" :disabled="saving || !options.units.length">{{ saving ? '建立中…' : '建立租約' }}</button></menu></form></dialog>

    <dialog ref="editLeaseDialog" class="modal admin-tenancy-dialog"><form method="dialog" @submit.prevent="submitEditLease"><div class="modal-head"><div><h3>修改租約</h3><small>{{ selectedRow?.leaseNo }} · 不會更換租客或單位</small></div><button type="button" class="icon-close" @click="closeDialog('editLeaseDialog')">×</button></div><div class="form-grid tenancy-form"><label>租客<input :value="selectedRow?.tenantName" disabled></label><label>出租單位<input :value="`${selectedRow?.projectName || ''} · ${selectedRow?.unitNo || ''}`" disabled></label><label>開始日期<input v-model="editLeaseForm.startDate" type="date" required></label><label>結束日期<input v-model="editLeaseForm.endDate" type="date" :min="todayDate" required></label><label>月租（RM）<input v-model.number="editLeaseForm.monthlyRent" type="number" min="0.01" step="0.01" required></label><label>押金（RM）<input v-model.number="editLeaseForm.depositAmount" type="number" min="0" step="0.01" required></label><label>每月繳租日<input v-model.number="editLeaseForm.paymentDay" type="number" min="1" max="31" required></label><div class="lease-change-note"><b>帳單更新規則</b><span>只調整本月起尚未付款且沒有收款記錄的帳單；已支付或部分支付帳單不追溯修改。</span></div><p v-if="actionError" class="admin-property-error">{{ actionError }}</p></div><menu><button type="button" @click="closeDialog('editLeaseDialog')">取消</button><button class="primary-btn" :disabled="saving">{{ saving ? '儲存中…' : '儲存租約' }}</button></menu></form></dialog>

    <dialog ref="transferLeaseDialog" class="modal admin-tenancy-dialog"><form method="dialog" @submit.prevent="submitTransferLease"><div class="modal-head"><div><h3>轉租</h3><small>{{ selectedRow?.projectName }} · {{ selectedRow?.unitNo }}</small></div><button type="button" class="icon-close" @click="closeDialog('transferLeaseDialog')">×</button></div><div class="form-grid tenancy-form"><label>原租客<input :value="selectedRow?.tenantName" disabled></label><label>承接租客<select v-model.number="transferLeaseForm.newTenantId" required><option :value="null" disabled>選擇新租客</option><option v-for="tenant in transferTenantOptions" :key="tenant.id" :value="tenant.id">{{ tenant.name }}</option></select></label><label>轉租生效日<input v-model="transferLeaseForm.transferDate" type="date" :min="transferMinDate" :max="selectedRow?.leaseEnd" required></label><label>新租約結束日<input v-model="transferLeaseForm.endDate" type="date" :min="transferLeaseForm.transferDate" required></label><label>新月租（RM）<input v-model.number="transferLeaseForm.monthlyRent" type="number" min="0.01" step="0.01" required></label><label>新押金（RM）<input v-model.number="transferLeaseForm.depositAmount" type="number" min="0" step="0.01" required></label><label>每月繳租日<input v-model.number="transferLeaseForm.paymentDay" type="number" min="1" max="31" required></label><label class="tenancy-contract-field">新租約文件（選填）<input type="file" accept="application/pdf,image/jpeg,image/png" @change="selectTransferContract"><small>原租約文件不會轉移到新租客</small></label><div class="lease-transfer-warning"><b>轉租不會轉移舊欠款</b><span>原租約會在生效日前一天結束並保留歷史；原租客未結清帳單仍歸原租約，新租客使用新的租約編號。</span></div><p v-if="!transferTenantOptions.length" class="admin-property-error">目前沒有其他啟用租客可承接租約</p><p v-if="actionError" class="admin-property-error">{{ actionError }}</p></div><menu><button type="button" @click="closeDialog('transferLeaseDialog')">取消</button><button class="primary-btn" :disabled="saving || !transferTenantOptions.length">{{ saving ? '轉租中…' : '確認轉租' }}</button></menu></form></dialog>

  </section>
</template>

<script>
import { createAdminLease, createAdminTenant, fetchAdminLeaseContract, fetchAdminTenancy, fetchAdminTenancyOptions, sendAdminRentReminder, transferAdminLease, updateAdminLease, uploadAdminLeaseContract } from '../services/propertyApi';
const today = () => new Date().toISOString().slice(0, 10);
const nextYear = () => { const date = new Date(); date.setFullYear(date.getFullYear() + 1); return date.toISOString().slice(0, 10); };
const plusDays = (value, days) => { const date = new Date(`${value}T00:00:00`); date.setDate(date.getDate() + days); return date.toISOString().slice(0, 10); };
export default {
  inject: ['page'],
  data() { return { rows: [], selectedId: null, totalRows: 0, totalPages: 1, pageNumber: 1, pageSize: 10, loading: false, errorMessage: '', saving: false, contractBusy: false, leaseContractFile: null, transferContractFile: null, actionError: '', requestSerial: 0, todayDate: today(), options: { projects: [], tenants: [], units: [] }, tenantForm: { fullName: '', identityNo: '', phone: '', email: '', status: 'active' }, leaseForm: { tenantId: null, unitId: null, startDate: today(), endDate: nextYear(), monthlyRent: 0, depositAmount: 0, paymentDay: 1 }, editLeaseForm: { startDate: '', endDate: '', monthlyRent: 0, depositAmount: 0, paymentDay: 1 }, transferLeaseForm: { newTenantId: null, transferDate: today(), endDate: '', monthlyRent: 0, depositAmount: 0, paymentDay: 1 } }; },
  computed: {
    selectedRow() { return this.rows.find(row => row.tenantId === this.selectedId) || this.rows[0] || null; },
    visiblePages() { const start = Math.max(1, Math.min(this.pageNumber - 2, this.totalPages - 4)); return Array.from({ length: Math.min(5, this.totalPages) }, (_, i) => start + i); },
    rentProgress() { return !Number(this.selectedRow?.amountDue) ? 0 : Math.min(100, Math.round(Number(this.selectedRow.amountPaid || 0) / Number(this.selectedRow.amountDue) * 100)); },
    tenantNonce() { return this.page.adminTenantCreateNonce; }, leaseNonce() { return this.page.adminLeaseCreateNonce; },
    transferTenantOptions() { return (this.options.tenants || []).filter(tenant => tenant.id !== this.selectedRow?.tenantId); },
    transferMinDate() { if (!this.selectedRow?.leaseStart) return this.todayDate; return [this.todayDate, plusDays(this.selectedRow.leaseStart, 1)].sort().at(-1); }
  },
  watch: {
    'page.moduleSearch'() { this.resetLoad(); }, 'page.globalSearch'() { this.resetLoad(); }, 'page.projectFilter'() { this.resetLoad(); }, 'page.statusFilter'() { this.resetLoad(); },
    pageSize() { this.pageNumber = 1; this.loadData(); }, tenantNonce(v, old) { if (v > old) this.openTenant(); }, leaseNonce(v, old) { if (v > old) this.openLease(); },
    rows: { deep: true, handler(rows) { if (!rows.some(row => row.tenantId === this.selectedId)) this.selectedId = rows[0]?.tenantId || null; } }
  },
  mounted() { this.page.projectFilter = '全部建案'; this.page.statusFilter = '全部狀態'; this.loadData(); },
  methods: {
    async loadData() { const serial = ++this.requestSerial; this.loading = true; this.errorMessage = ''; try { const [response, options] = await Promise.all([fetchAdminTenancy({ page: this.pageNumber, pageSize: this.pageSize, keyword: this.page.globalSearch || this.page.moduleSearch || '', projectName: String(this.page.projectFilter || '').includes('全部') ? '' : this.page.projectFilter, status: this.statusParam(this.page.statusFilter) }), fetchAdminTenancyOptions()]); if (serial !== this.requestSerial) return; this.rows = response.rows || []; this.totalRows = response.page?.totalRows || 0; this.totalPages = response.page?.totalPages || 1; this.pageNumber = response.page?.page || 1; this.options = options || { projects: [], tenants: [], units: [] }; this.page.adminTenancyProjects = this.options.projects || []; this.page.adminTenancyMetrics = this.metrics(response.summary || {}); this.page.adminTenancyExportHeaders = ['租客', '建案', '單位', '租約編號', '租期開始', '租期結束', '月租', '本期應收', '已收', '未收', '租金狀態']; this.page.adminTenancyExportRows = this.rows.map(row => [row.tenantName, row.projectName || '', row.unitNo || '', row.leaseNo || '', row.leaseStart || '', row.leaseEnd || '', row.monthlyRent, row.amountDue, row.amountPaid, row.amountUnpaid, this.rentLabel(row.rentStatus)]); } catch (e) { if (serial !== this.requestSerial) return; this.rows = []; this.errorMessage = e.message || 'API request failed'; this.page.adminTenancyMetrics = null; this.page.adminTenancyExportRows = []; } finally { if (serial === this.requestSerial) this.loading = false; } },
    metrics(s) { return [{ icon: '租', label: '租客總數', value: `${Number(s.tenantCount || 0)} 位`, delta: `${Number(s.activeLeaseCount || 0)} 份有效租約`, trend: 'up' }, { icon: '款', label: '本月應收租金', value: this.money(s.currentDue), delta: '資料庫即時計算', trend: 'up' }, { icon: '✓', label: '本月已收租金', value: this.money(s.currentPaid), delta: '已入帳收款', trend: 'up' }, { icon: '!', label: '未收金額', value: this.money(s.currentUnpaid), delta: '需要跟進', trend: Number(s.currentUnpaid) ? 'down' : 'up' }, { icon: '部', label: '部分收款筆數', value: `${Number(s.partialCount || 0)} 筆`, delta: '本月帳單', trend: Number(s.partialCount) ? 'down' : '' }, { icon: '逾', label: '逾期租金筆數', value: `${Number(s.overdueCount || 0)} 筆`, delta: '本月帳單', trend: Number(s.overdueCount) ? 'down' : 'up' }]; },
    resetLoad() { this.pageNumber = 1; this.loadData(); }, goPage(n) { if (n >= 1 && n <= this.totalPages && n !== this.pageNumber) { this.pageNumber = n; this.loadData(); } },
    openTenant() { this.tenantForm = { fullName: '', identityNo: '', phone: '', email: '', status: 'active' }; this.actionError = ''; this.$refs.tenantDialog?.showModal(); },
    openLease() { this.leaseForm = { tenantId: this.selectedRow?.tenantId || null, unitId: null, startDate: today(), endDate: nextYear(), monthlyRent: 0, depositAmount: 0, paymentDay: 1 }; this.leaseContractFile = null; this.actionError = ''; this.$refs.leaseDialog?.showModal(); },
    closeDialog(ref) { this.$refs[ref]?.close(); this.actionError = ''; },
    async submitTenant() { this.saving = true; this.actionError = ''; try { await createAdminTenant(this.tenantForm); this.closeDialog('tenantDialog'); await this.loadData(); this.page.showToast('租客已建立'); } catch (e) { this.actionError = e.message || '建立租客失敗'; } finally { this.saving = false; } },
    async submitLease() { this.saving = true; this.actionError = ''; try { const created = await createAdminLease(this.leaseForm); if (this.leaseContractFile) { try { await uploadAdminLeaseContract(created.id, this.leaseContractFile); } catch (uploadError) { this.closeDialog('leaseDialog'); await this.loadData(); this.page.showToast(`租約已建立，但文件上傳失敗：${uploadError.message}`); return; } } this.closeDialog('leaseDialog'); await this.loadData(); this.page.showToast(this.leaseContractFile ? '租約、文件與本月帳單已建立' : '租約與本月帳單已建立'); } catch (e) { this.actionError = e.message || '建立租約失敗'; } finally { this.saving = false; } },
    openEditLease() { if (!this.selectedRow?.leaseId || this.selectedRow.leaseStatus !== 'active') return; this.editLeaseForm = { startDate: this.selectedRow.leaseStart, endDate: this.selectedRow.leaseEnd, monthlyRent: Number(this.selectedRow.monthlyRent), depositAmount: Number(this.selectedRow.depositAmount), paymentDay: Number(this.selectedRow.paymentDay) }; this.actionError = ''; this.$refs.editLeaseDialog?.showModal(); },
    async submitEditLease() { this.saving = true; this.actionError = ''; try { await updateAdminLease(this.selectedRow.leaseId, this.editLeaseForm); this.closeDialog('editLeaseDialog'); await this.loadData(); this.page.showToast('租約資料已更新'); } catch (e) { this.actionError = e.message || '租約修改失敗'; } finally { this.saving = false; } },
    openTransferLease() { if (!this.selectedRow?.leaseId || this.selectedRow.leaseStatus !== 'active') return; this.transferLeaseForm = { newTenantId: null, transferDate: this.transferMinDate, endDate: this.selectedRow.leaseEnd, monthlyRent: Number(this.selectedRow.monthlyRent), depositAmount: Number(this.selectedRow.depositAmount), paymentDay: Number(this.selectedRow.paymentDay) }; this.transferContractFile = null; this.actionError = ''; this.$refs.transferLeaseDialog?.showModal(); },
    selectTransferContract(event) { const file = event.target.files?.[0] || null; if (file && !this.validContract(file)) { event.target.value = ''; return; } this.transferContractFile = file; },
    async submitTransferLease() { this.saving = true; this.actionError = ''; try { const oldLeaseId = this.selectedRow.leaseId; const newTenantId = this.transferLeaseForm.newTenantId; const created = await transferAdminLease(oldLeaseId, this.transferLeaseForm); if (this.transferContractFile) { try { await uploadAdminLeaseContract(created.id, this.transferContractFile); } catch (uploadError) { this.closeDialog('transferLeaseDialog'); this.selectedId = newTenantId; await this.loadData(); this.page.showToast(`轉租已完成，但新租約文件上傳失敗：${uploadError.message}`); return; } } this.closeDialog('transferLeaseDialog'); this.selectedId = newTenantId; await this.loadData(); this.page.showToast(this.transferContractFile ? '轉租及新租約文件已完成' : '轉租已完成'); } catch (e) { this.actionError = e.message || '轉租失敗'; } finally { this.saving = false; } },
    selectNewLeaseContract(event) { const file = event.target.files?.[0] || null; if (file && !this.validContract(file)) { event.target.value = ''; return; } this.leaseContractFile = file; },
    chooseContract() { if (!this.selectedRow?.leaseId || this.contractBusy) return; this.$refs.contractInput.value = ''; this.$refs.contractInput.click(); },
    async uploadSelectedContract(event) { const file = event.target.files?.[0]; if (!file || !this.validContract(file)) return; const replacing = Boolean(this.selectedRow?.contractDocumentId); this.contractBusy = true; try { await uploadAdminLeaseContract(this.selectedRow.leaseId, file); await this.loadData(); this.page.showToast(replacing ? '租約文件已更換' : '租約文件已上傳'); } catch (e) { this.page.showToast(e.message || '租約文件上傳失敗'); } finally { this.contractBusy = false; event.target.value = ''; } },
    async viewContract() { await this.openContract(false); },
    async downloadContract() { await this.openContract(true); },
    async openContract(download) { if (!this.selectedRow?.leaseId) return; this.contractBusy = true; try { const result = await fetchAdminLeaseContract(this.selectedRow.leaseId, download); const url = URL.createObjectURL(result.blob); if (download) { const link = document.createElement('a'); link.href = url; link.download = this.selectedRow.contractDocumentName || `lease-contract-${this.selectedRow.leaseId}`; link.click(); URL.revokeObjectURL(url); } else { window.open(url, '_blank', 'noopener'); setTimeout(() => URL.revokeObjectURL(url), 60000); } } catch (e) { this.page.showToast(e.message || (download ? '租約下載失敗' : '租約預覽失敗')); } finally { this.contractBusy = false; } },
    validContract(file) { const types = ['application/pdf', 'image/jpeg', 'image/png']; if (!types.includes(file.type) || file.size > 10 * 1024 * 1024) { this.page.showToast('只支援 10MB 以內的 PDF、JPG 或 PNG 租約文件'); return false; } return true; },
    async sendReminder() { try { await sendAdminRentReminder(this.selectedRow.invoiceId); this.page.showToast('租金提醒已建立'); } catch (e) { this.page.showToast(e.message || '提醒建立失敗'); } },
    statusParam(v) { return ({ '已收': 'paid', '部分收款': 'partial', '待收': 'unpaid', '逾期': 'overdue' })[v] || ''; },
    rentLabel(v) { return ({ paid: '已收', partial: '部分收款', unpaid: '待收', overdue: '逾期', no_invoice: '未出帳' })[v] || '未出帳'; },
    rentClass(v) { return v === 'paid' ? 'green' : v === 'overdue' ? 'red' : v === 'partial' || v === 'unpaid' ? 'orange' : 'gray'; },
    money(v) { return `RM ${Number(v || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }, initials(name) { return String(name || '').split(/\s+/).slice(0, 2).map(p => p[0]).join('').toUpperCase() || '租'; }
  }
};
</script>

<style scoped>
.lease-change-note,.lease-transfer-warning{grid-column:1/-1;display:grid;gap:5px;padding:11px 13px;border:1px solid #d9e3ed;border-radius:8px;background:#f6f9fc;color:#53667b;font-size:12px}.lease-change-note b{color:#12375f}.lease-transfer-warning{border-color:#efd28b;background:#fff8e7;color:#78570a}.lease-transfer-warning b{color:#8b5d00}.tenancy-actions button:first-child{background:#0b376c;color:#fff;border-color:#0b376c}.tenancy-actions button:disabled{opacity:.5;cursor:not-allowed}
</style>
