CREATE TABLE IF NOT EXISTS admin_recycle_bin (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  entity_type VARCHAR(20) NOT NULL COMMENT 'expense / maintenance',
  entity_id BIGINT UNSIGNED NOT NULL,
  finance_record_id BIGINT UNSIGNED NULL,
  work_order_id BIGINT UNSIGNED NULL,
  previous_payment_status VARCHAR(30) NULL,
  previous_confirmation_status VARCHAR(30) NULL,
  previous_sync_status VARCHAR(30) NULL,
  previous_payment_method VARCHAR(40) NULL,
  previous_reserve_account_id BIGINT UNSIGNED NULL,
  previous_reserve_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  previous_maintenance_status VARCHAR(30) NULL,
  deleted_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  restored_by BIGINT UNSIGNED NULL,
  restored_at DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_admin_recycle_active (entity_type, entity_id, restored_at, expires_at),
  KEY idx_admin_recycle_expiry (expires_at, restored_at),
  CONSTRAINT fk_admin_recycle_finance FOREIGN KEY (finance_record_id) REFERENCES finance_records (id),
  CONSTRAINT fk_admin_recycle_work_order FOREIGN KEY (work_order_id) REFERENCES maintenance_work_orders (id),
  CONSTRAINT fk_admin_recycle_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id),
  CONSTRAINT fk_admin_recycle_restored_by FOREIGN KEY (restored_by) REFERENCES users (id)
) ENGINE=InnoDB;
