CREATE TABLE IF NOT EXISTS property_handovers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  mandate_id BIGINT UNSIGNED NOT NULL,
  handover_date DATE NOT NULL,
  condition_summary VARCHAR(2000) NULL,
  key_count INT UNSIGNED NOT NULL DEFAULT 0,
  access_card_count INT UNSIGNED NOT NULL DEFAULT 0,
  water_meter VARCHAR(120) NULL,
  electricity_meter VARCHAR(120) NULL,
  inventory JSON NULL,
  received_by VARCHAR(160) NULL,
  notes VARCHAR(1000) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  completed_by BIGINT UNSIGNED NULL,
  completed_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id), UNIQUE KEY uk_property_handovers_mandate (mandate_id),
  KEY idx_property_handovers_status (status, handover_date),
  CONSTRAINT fk_property_handovers_mandate FOREIGN KEY (mandate_id) REFERENCES rental_mandates (id),
  CONSTRAINT fk_property_handovers_completed_by FOREIGN KEY (completed_by) REFERENCES users (id),
  CONSTRAINT fk_property_handovers_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT chk_property_handovers_status CHECK (status IN ('draft','completed'))
) ENGINE=InnoDB;
