<template>
  <section class="content-grid admin-tenancy-workspace">
    <div class="panel table-panel tenancy-list-panel">
      <div class="panel-head"><div><h2>{{ $t('legacy.t_d8a78b14bb2e') }}</h2><span>{{ totalRows }} {{ $t('legacy.t_86761b63a7bd') }}</span></div><span v-if="loading" class="tenancy-loading">{{ $t('legacy.t_6ce3778a43cd') }}</span></div>
      <div v-if="errorMessage" class="admin-owner-state error"><strong>{{ $t('legacy.t_f5ec447609a8') }}</strong><span>{{ errorMessage }}</span><button @click="loadData">{{ $t('legacy.t_0c9157b5bfac') }}</button></div>
      <div v-else class="table-wrap tenancy-table-wrap">
        <table>
          <thead><tr><th>{{ $t('legacy.t_42c950a2ce7c') }}</th><th>{{ $t('legacy.t_114246450ff0') }}</th><th>{{ $t('legacy.t_bd95f007d6d0') }}</th><th>{{ $t('legacy.t_a7ff541f4978') }}</th><th>{{ $t('legacy.t_fdeda5befee2') }}</th><th>{{ $t('legacy.t_17973bd1a231') }}</th><th>{{ $t('legacy.t_84ae58f16b57') }}</th><th>{{ $t('legacy.t_53ebb183604b') }}</th><th>{{ $t('legacy.t_d71d167d09d9') }}</th><th>{{ $t('legacy.t_f3ea6d345e2a') }}</th></tr></thead>
          <tbody>
            <tr v-for="row in rows" :key="row.leaseId ? `lease-${row.leaseId}` : `tenant-${row.tenantId}`" :class="{ selected: row === selectedRow }" @click="selectRow(row)">
              <td><strong>{{ row.tenantName }}</strong><small>{{ row.phone || row.email || $t('legacy.t_33ebf8c2736b') }}</small></td>
              <td>{{ row.projectName || $t('legacy.t_bc6d72467bec') }}<small>{{ row.unitNo || '—' }}</small></td>
              <td>{{ row.leaseNo || '—' }}<small v-if="row.leaseStart">{{ row.leaseStart }} ~ {{ row.leaseEnd }}</small></td>
              <td>{{ row.billingMonth || '—' }}</td>
              <td><b>{{ money(row.amountDue) }}</b></td>
              <td><span class="tenancy-paid">{{ money(row.amountPaid) }}</span><small class="tenancy-unpaid">{{ $t('legacy.t_58bb21f07dc4') }} {{ money(row.amountUnpaid) }}</small></td>
              <td><b class="money-red">{{ money(row.totalUnpaid) }}</b><small class="tenancy-unpaid">{{ $t('legacy.t_57dd08dd1420') }}</small></td>
              <td>{{ row.dueDate || '—' }}</td>
              <td><span class="tag" :class="rentClass(row.rentStatus)">{{ rentLabel(row.rentStatus) }}</span></td>
              <td><button type="button" class="row-actions tenancy-detail-button" :title="$t('legacy.t_eed616a2b4cf')" :aria-label="$t('legacy.t_eed616a2b4cf')" :disabled="!row.leaseId" @click.stop="openInvoiceDetails(row)"><svg class="tenancy-detail-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3h8l3 3v15H7zM15 3v4h4M10 11h5M10 15h5M10 19h3"/></svg></button></td>
            </tr>
            <tr v-if="!loading && !rows.length"><td colspan="10" class="admin-owner-empty">{{ $t('legacy.t_6d6a0646edc9') }}</td></tr>
          </tbody>
        </table>
      </div>
      <div class="pager"><span>{{ $t('legacy.t_3b6ef811b85a') }} {{ totalRows }} {{ $t('legacy.t_86761b63a7bd') }}</span><div class="admin-building-pager"><button :disabled="pageNumber <= 1" @click="goPage(pageNumber - 1)">&lt;</button><button v-for="n in visiblePages" :key="n" :class="{ active: n === pageNumber }" @click="goPage(n)">{{ n }}</button><button :disabled="pageNumber >= totalPages" @click="goPage(pageNumber + 1)">&gt;</button><select v-model.number="pageSize"><option :value="10">{{ $t('legacy.t_fc6da0e815a1') }}</option><option :value="20">{{ $t('legacy.t_93d673672fa5') }}</option><option :value="50">{{ $t('legacy.t_529930b886d2') }}</option></select></div></div>
    </div>

    <aside class="panel detail-panel tenancy-detail-panel">
      <div v-if="selectedRow" class="detail-card">
        <div class="profile tenancy-profile"><div class="big-avatar">{{ initials(selectedRow.tenantName) }}</div><div><h3>{{ selectedRow.tenantName }}</h3><p>{{ selectedRow.projectName || $t('legacy.t_bc6d72467bec') }} · {{ selectedRow.unitNo || '—' }}</p></div><span class="tag" :class="rentClass(selectedRow.rentStatus)">{{ rentLabel(selectedRow.rentStatus) }}</span></div>
        <div class="detail-actions tenancy-actions">
          <button :disabled="selectedRow.leaseStatus !== 'active'" @click="openEditLease">{{ $t('legacy.t_f688a08a4a7e') }}</button>
          <button :disabled="selectedRow.leaseStatus !== 'active'" @click="openTransferLease">{{ $t('legacy.t_40cd2e301851') }}</button>
          <button v-if="selectedRow.contractDocumentId" :disabled="contractBusy" @click="viewContract">{{ $t('legacy.t_b509f0c1aa40') }}</button>
          <button v-if="selectedRow.contractDocumentId" :disabled="contractBusy" @click="downloadContract">{{ $t('legacy.t_6c77930aa132') }}</button>
          <button v-if="selectedRow.leaseId && !selectedRow.contractSigned && selectedRow.contractStatus !== 'signed'" :disabled="contractBusy || templateBusy" @click="openLeaseSigning">{{ $t('legacy.t_403f901d0b71') }}</button>
          <button :disabled="!selectedRow.leaseId || templateBusy" @click="openTemplateGenerator('otr')">{{ $t('tenancy.generateOtr') }}</button>
          <button :disabled="!selectedRow.leaseId || templateBusy" @click="openTemplateGenerator('tenancy-agreement')">{{ $t('tenancy.generateTenancyAgreement') }}</button>
          <button :disabled="!selectedRow.leaseId || contractBusy" @click="chooseContract">
            {{ contractBusy ? $t('legacy.t_1e038f9b55ec') : selectedRow.contractDocumentId ? $t('legacy.t_40c1e1193976') : $t('legacy.t_230cac2ff1e6') }}
          </button>
          <input ref="contractInput" type="file" accept="application/pdf,image/jpeg,image/png" style="display:none" @change="uploadSelectedContract">
          <button :disabled="!selectedRow.invoiceId || !Number(selectedRow.amountUnpaid)" @click="sendReminder">{{ $t('legacy.t_0bdaef716172') }}</button>
        </div>
        <div class="detail-section"><h4><span class="num">{{ $t('legacy.t_356a192b7913') }}</span>{{ $t('legacy.t_2c7d5d60a874') }}</h4><div class="kv"><span>{{ $t('legacy.t_3b08982cc350') }}</span><b>{{ selectedRow.identityNo || '—' }}</b></div><div class="kv"><span>{{ $t('legacy.t_7177787c6e84') }}</span><b>{{ selectedRow.phone || '—' }}</b></div><div class="kv"><span>{{ $t('legacy.t_84add5b29527') }}</span><b>{{ selectedRow.email || '—' }}</b></div><div class="kv"><span>{{ $t('legacy.t_45293595eae3') }}</span><b>{{ selectedRow.tenantStatus === 'active' ? $t('legacy.t_ce6c3dc32674') : $t('legacy.t_d989e55188c9') }}</b></div></div>
        <div class="detail-section"><h4><span class="num">{{ $t('legacy.t_da4b9237bacc') }}</span>{{ $t('legacy.t_1a855f8f0f4f') }}</h4><div class="kv"><span>{{ $t('legacy.t_7275c423eae7') }}</span><b>{{ selectedRow.leaseNo || '—' }}</b></div><div class="kv"><span>{{ $t('legacy.t_87d24fa26e57') }}</span><b>{{ selectedRow.leaseStart ? `${selectedRow.leaseStart} ~ ${selectedRow.leaseEnd}` : '—' }}</b></div><div class="kv"><span>{{ $t('legacy.t_4c32ed4c883c') }}</span><b>{{ money(selectedRow.monthlyRent) }}</b></div><div class="kv"><span>{{ $t('legacy.t_986f8c25c20e') }}</span><b>{{ selectedRow.rentCalculationMethod === 'daily_prorated' ? $t('legacy.t_1e5825e68267') : $t('legacy.t_b9c6778f8e79') }}</b></div><div class="kv"><span>{{ $t('legacy.t_52661b02b6a2') }}</span><b>{{ money(selectedRow.depositAmount) }}</b></div><div class="kv"><span>{{ $t('legacy.t_59e1119803f6') }}</span><b>{{ selectedRow.paymentDay ? `${selectedRow.paymentDay} 日` : '—' }}</b></div><div class="kv"><span>{{ $t('legacy.t_56e5d9db491b') }}</span><b>{{ selectedRow.contractDocumentName || $t('legacy.t_3c5b845dce11') }}</b></div><div class="kv"><span>{{ $t('legacy.t_f365bb04b619') }}</span><b>{{ contractStatusLabel(selectedRow.contractStatus) }}</b></div></div>
        <div class="detail-section"><h4><span class="num">{{ $t('legacy.t_77de68daecd8') }}</span>{{ $t('legacy.t_edeb2ce5b99b') }}</h4><div class="kv"><span>{{ $t('legacy.t_a7ff541f4978') }}</span><b>{{ selectedRow.billingMonth || '—' }}</b></div><div class="kv"><span>{{ $t('legacy.t_60a54ee472f7') }}</span><b>{{ money(selectedRow.amountDue) }}</b></div><div class="kv"><span>{{ $t('legacy.t_109f4a1ff366') }}</span><b class="tenancy-paid">{{ money(selectedRow.amountPaid) }}</b></div><div class="kv"><span>{{ $t('legacy.t_c08daf0f9b3a') }}</span><b class="money-red">{{ money(selectedRow.amountUnpaid) }}</b></div><div class="kv"><span>{{ $t('legacy.t_84ae58f16b57') }}</span><b class="money-red">{{ money(selectedRow.totalUnpaid) }}</b></div><div class="kv"><span>{{ $t('tenancy.prepaidRentBalance') }}</span><b class="tenancy-paid">{{ money(selectedRow.prepaidRentBalance) }}</b></div><button class="tenancy-invoice-link" :disabled="!selectedRow.leaseId" @click="openInvoiceDetails(selectedRow)">{{ $t('legacy.t_63e1e4b3444e') }}</button><div class="progress"><i :style="{ width: rentProgress + '%' }"></i></div></div>
      </div>
      <div v-else class="admin-owner-empty">{{ $t('legacy.t_e02ba98c2bb5') }}</div>
    </aside>

    <dialog ref="tenantDialog" class="modal admin-tenancy-dialog"><form method="dialog" @submit.prevent="submitTenant"><div class="modal-head"><div><h3>{{ $t('legacy.t_cae78ebbbaa6') }}</h3><small>{{ $t('legacy.t_478c437c8a9f') }}</small></div><button type="button" class="icon-close" @click="closeDialog('tenantDialog')">×</button></div><div class="form-grid tenancy-form"><label>{{ $t('legacy.t_235873c711c8') }}<input v-model.trim="tenantForm.fullName" required maxlength="160"></label><label>{{ $t('legacy.t_3b08982cc350') }}<input v-model.trim="tenantForm.identityNo" maxlength="120"></label><label>{{ $t('legacy.t_7177787c6e84') }}<input v-model.trim="tenantForm.phone" maxlength="40"></label><label>{{ $t('legacy.t_84add5b29527') }}<input v-model.trim="tenantForm.email" type="email" maxlength="190"></label><label>{{ $t('legacy.t_45293595eae3') }}<select v-model="tenantForm.status"><option value="active">{{ $t('legacy.t_ce6c3dc32674') }}</option><option value="inactive">{{ $t('legacy.t_d989e55188c9') }}</option></select></label><p v-if="actionError" class="admin-property-error">{{ actionError }}</p></div><menu><button type="button" @click="closeDialog('tenantDialog')">{{ $t('legacy.t_4d0b4688c787') }}</button><button class="primary-btn" :disabled="saving">{{ saving ? $t('legacy.t_2cd5496ec548') : $t('legacy.t_30e6d69fa298') }}</button></menu></form></dialog>

    <dialog ref="leaseDialog" class="modal admin-tenancy-dialog"><form method="dialog" @submit.prevent="submitLease"><div class="modal-head"><div><h3>{{ $t('legacy.t_c6693d2dde44') }}</h3><small>{{ $t('legacy.t_4340ea14c893') }}</small></div><button type="button" class="icon-close" @click="closeDialog('leaseDialog')">×</button></div><div class="form-grid tenancy-form"><label>{{ $t('legacy.t_42c950a2ce7c') }}<select v-model.number="leaseForm.tenantId" required><option :value="null" disabled>{{ $t('legacy.t_6c362bcd7b18') }}</option><option v-for="t in options.tenants" :key="t.id" :value="t.id">{{ t.name }}</option></select></label><label>{{ $t('legacy.t_53be6696e334') }}<select v-model.number="leaseForm.unitId" required @change="applyMandateDates"><option :value="null" disabled>{{ $t('legacy.t_e47eccacd8d5') }}</option><option v-for="u in options.units" :key="u.id" :value="u.id">{{ u.projectName }} · {{ u.unitNo }}{{ $t('legacy.t_046cd5be4477') }} {{ u.mandateStartDate }}～{{ u.mandateEndDate || $t('legacy.t_a1c6185187c0') }}）</option></select></label><label>{{ $t('legacy.t_7fd7a227e9ce') }}<input v-model="leaseForm.startDate" type="date" :min="selectedLeaseUnit?.mandateStartDate" :max="selectedLeaseUnit?.mandateEndDate || undefined" required></label><label>{{ $t('legacy.t_27eefa5237a0') }}<input v-model="leaseForm.endDate" type="date" :min="leaseForm.startDate || selectedLeaseUnit?.mandateStartDate" :max="selectedLeaseUnit?.mandateEndDate || undefined" required></label><label>{{ $t('legacy.t_2454bfeb3505') }}<input v-model.number="leaseForm.monthlyRent" type="number" min="0.01" step="0.01" required></label><label>{{ $t('legacy.t_40cf1ff4d13b') }}<input v-model.number="leaseForm.depositAmount" type="number" min="0" step="0.01" required></label><label>{{ $t('legacy.t_59e1119803f6') }}<input v-model.number="leaseForm.paymentDay" type="number" min="1" max="31" required></label><label>{{ $t('legacy.t_4611dc09098c') }}<select v-model="leaseForm.rentCalculationMethod"><option value="monthly">{{ $t('legacy.t_b9c6778f8e79') }}</option><option value="daily_prorated">{{ $t('legacy.t_1e5825e68267') }}</option></select><small>{{ $t('legacy.t_adb5a9114c62') }}</small></label><label class="tenancy-contract-field">{{ $t('legacy.t_964d1e8f91d4') }}<input type="file" accept="application/pdf,image/jpeg,image/png" @change="selectNewLeaseContract"><small>{{ $t('legacy.t_f46a65c7a59f') }}</small></label><p v-if="!options.units.length" class="admin-property-error">{{ $t('legacy.t_526945c6d6cf') }}</p><p v-if="actionError" class="admin-property-error">{{ actionError }}</p></div><menu><button type="button" @click="closeDialog('leaseDialog')">{{ $t('legacy.t_4d0b4688c787') }}</button><button class="primary-btn" :disabled="saving || !options.units.length">{{ saving ? $t('legacy.t_2cd5496ec548') : $t('legacy.t_aced24f70328') }}</button></menu></form></dialog>

    <dialog ref="editLeaseDialog" class="modal admin-tenancy-dialog"><form method="dialog" @submit.prevent="submitEditLease"><div class="modal-head"><div><h3>{{ $t('legacy.t_f688a08a4a7e') }}</h3><small>{{ selectedRow?.leaseNo }} {{ $t('legacy.t_b4e63cbfb7fd') }}</small></div><button type="button" class="icon-close" @click="closeDialog('editLeaseDialog')">×</button></div><div class="form-grid tenancy-form"><label>{{ $t('legacy.t_42c950a2ce7c') }}<input :value="selectedRow?.tenantName" disabled></label><label>{{ $t('legacy.t_53be6696e334') }}<input :value="`${selectedRow?.projectName || ''} · ${selectedRow?.unitNo || ''}`" disabled></label><label>{{ $t('legacy.t_7fd7a227e9ce') }}<input v-model="editLeaseForm.startDate" type="date" required></label><label>{{ $t('legacy.t_27eefa5237a0') }}<input v-model="editLeaseForm.endDate" type="date" :min="todayDate" required></label><label>{{ $t('legacy.t_2454bfeb3505') }}<input v-model.number="editLeaseForm.monthlyRent" type="number" min="0.01" step="0.01" required></label><label>{{ $t('legacy.t_40cf1ff4d13b') }}<input v-model.number="editLeaseForm.depositAmount" type="number" min="0" step="0.01" required></label><label>{{ $t('legacy.t_59e1119803f6') }}<input v-model.number="editLeaseForm.paymentDay" type="number" min="1" max="31" required></label><label>{{ $t('legacy.t_4611dc09098c') }}<select v-model="editLeaseForm.rentCalculationMethod"><option value="monthly">{{ $t('legacy.t_b9c6778f8e79') }}</option><option value="daily_prorated">{{ $t('legacy.t_1e5825e68267') }}</option></select></label><div class="lease-change-note"><b>{{ $t('legacy.t_95d145ab0c65') }}</b><span>{{ $t('legacy.t_4e86700a46b3') }}</span></div><p v-if="actionError" class="admin-property-error">{{ actionError }}</p></div><menu><button type="button" @click="closeDialog('editLeaseDialog')">{{ $t('legacy.t_4d0b4688c787') }}</button><button class="primary-btn" :disabled="saving">{{ saving ? $t('legacy.t_8488ea2522af') : $t('legacy.t_a08367c3ad9b') }}</button></menu></form></dialog>

    <dialog ref="transferLeaseDialog" class="modal admin-tenancy-dialog"><form method="dialog" @submit.prevent="submitTransferLease"><div class="modal-head"><div><h3>{{ $t('legacy.t_40cd2e301851') }}</h3><small>{{ selectedRow?.projectName }} · {{ selectedRow?.unitNo }}</small></div><button type="button" class="icon-close" @click="closeDialog('transferLeaseDialog')">×</button></div><div class="form-grid tenancy-form"><label>{{ $t('legacy.t_3be587f9d5f3') }}<input :value="selectedRow?.tenantName" disabled></label><label>{{ $t('legacy.t_1d18a8d9157c') }}<select v-model.number="transferLeaseForm.newTenantId" required><option :value="null" disabled>{{ $t('legacy.t_d58d5216e6aa') }}</option><option v-for="tenant in transferTenantOptions" :key="tenant.id" :value="tenant.id">{{ tenant.name }}</option></select></label><label>{{ $t('legacy.t_48631b2f5f6d') }}<input v-model="transferLeaseForm.transferDate" type="date" :min="transferMinDate" :max="selectedRow?.leaseEnd" required></label><label>{{ $t('legacy.t_4f265263cb6b') }}<input v-model="transferLeaseForm.endDate" type="date" :min="transferLeaseForm.transferDate" required></label><label>{{ $t('legacy.t_3dd7ca3f56b6') }}<input v-model.number="transferLeaseForm.monthlyRent" type="number" min="0.01" step="0.01" required></label><label>{{ $t('legacy.t_c6e11bda27b7') }}<input v-model.number="transferLeaseForm.depositAmount" type="number" min="0" step="0.01" required></label><label>{{ $t('legacy.t_59e1119803f6') }}<input v-model.number="transferLeaseForm.paymentDay" type="number" min="1" max="31" required></label><label>{{ $t('legacy.t_4611dc09098c') }}<select v-model="transferLeaseForm.rentCalculationMethod"><option value="monthly">{{ $t('legacy.t_b9c6778f8e79') }}</option><option value="daily_prorated">{{ $t('legacy.t_1e5825e68267') }}</option></select></label><label class="tenancy-contract-field">{{ $t('legacy.t_19faa1d83b11') }}<input type="file" accept="application/pdf,image/jpeg,image/png" @change="selectTransferContract"><small>{{ $t('legacy.t_d459e4c4dfb1') }}</small></label><div class="lease-transfer-warning"><b>{{ $t('legacy.t_787486055d66') }}</b><span>{{ $t('legacy.t_9ea4c2af4433') }}</span></div><p v-if="!transferTenantOptions.length" class="admin-property-error">{{ $t('legacy.t_d0d5dd05c114') }}</p><p v-if="actionError" class="admin-property-error">{{ actionError }}</p></div><menu><button type="button" @click="closeDialog('transferLeaseDialog')">{{ $t('legacy.t_4d0b4688c787') }}</button><button class="primary-btn" :disabled="saving || !transferTenantOptions.length">{{ saving ? $t('legacy.t_e42afa900cb7') : $t('legacy.t_a9e87ad0d750') }}</button></menu></form></dialog>

    <dialog ref="invoiceDetailsDialog" class="modal admin-tenancy-dialog tenancy-invoice-dialog"><div class="modal-head"><div><h3>{{ $t('legacy.t_6c6010c77d79') }}</h3><small>{{ invoiceDetailTitle }} {{ $t('legacy.t_6cc98689cde4') }}</small></div><button type="button" class="icon-close" @click="closeDialog('invoiceDetailsDialog')">×</button></div><div v-if="invoiceDetailsLoading" class="admin-owner-empty">{{ $t('legacy.t_46cbac9efcc4') }}</div><div v-else-if="invoiceDetailsError" class="admin-property-error">{{ invoiceDetailsError }}</div><div v-else class="table-wrap"><table><thead><tr><th>{{ $t('legacy.t_a7ff541f4978') }}</th><th>{{ $t('legacy.t_11cb5e87977f') }}</th><th>{{ $t('legacy.t_60a54ee472f7') }}</th><th>{{ $t('legacy.t_6cb2798516e3') }}</th><th>{{ $t('legacy.t_58bb21f07dc4') }}</th><th>{{ $t('legacy.t_45293595eae3') }}</th></tr></thead><tbody><tr v-for="invoice in invoiceDetails" :key="invoice.invoiceId"><td>{{ invoice.billingMonth }}</td><td>{{ invoice.dueDate }}</td><td>{{ money(invoice.amountDue) }}</td><td class="tenancy-paid">{{ money(invoice.amountPaid) }}</td><td class="money-red">{{ money(invoice.amountUnpaid) }}</td><td><span class="tag" :class="rentClass(invoice.rentStatus)">{{ rentLabel(invoice.rentStatus) }}</span></td></tr><tr v-if="!invoiceDetails.length"><td colspan="6" class="admin-owner-empty">{{ $t('legacy.t_6b0cbf3fea8e') }}</td></tr></tbody></table></div><menu><button type="button" @click="closeDialog('invoiceDetailsDialog')">{{ $t('legacy.t_ddc05404b0d6') }}</button></menu></dialog>
    <dialog ref="templateDialog" class="modal admin-tenancy-dialog contract-template-dialog">
      <form method="dialog" @submit.prevent="generateTemplate">
        <div class="modal-head"><div><h3>{{ templateForm.templateType === 'tenancy-agreement' ? $t('tenancy.generateTenancyAgreementTitle') : $t('tenancy.generateOtrTitle') }}</h3><small>{{ $t('tenancy.templateHint') }}</small></div><button type="button" class="icon-close" @click="closeDialog('templateDialog')">×</button></div>
        <div class="form-grid tenancy-form">
          <label>{{ $t('tenancy.caseNo') }}<input v-model.trim="templateForm.fields.caseNo" required></label>
          <label>{{ $t('tenancy.propertyAddress') }}<input v-model.trim="templateForm.fields.propertyAddress" required></label>
          <label>{{ $t('tenancy.ownerName') }}<input v-model.trim="templateForm.fields.landlordName"></label>
          <label>{{ $t('tenancy.ownerIdentity') }}<input v-model.trim="templateForm.fields.landlordIdentity"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.ownerAddress') }}<input v-model.trim="templateForm.fields.landlordAddress"></label>
          <label v-if="templateForm.templateType === 'otr'">{{ $t('tenancy.tenantName') }}<input v-model.trim="templateForm.fields.tenantName" required></label>
          <label v-if="templateForm.templateType === 'otr'">{{ $t('tenancy.tenantIdentity') }}<input v-model.trim="templateForm.fields.tenantIdentity"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.tenantName') }}<input v-model.trim="templateForm.fields.tenantName" required></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.tenantIdentity') }}<input v-model.trim="templateForm.fields.tenantIdentity"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.tenantPhone') }}<input v-model.trim="templateForm.fields.tenantPhone"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.tenantAddress') }}<input v-model.trim="templateForm.fields.tenantAddress"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.tenantEmail') }}<input v-model.trim="templateForm.fields.tenantEmail" type="email"></label>
          <label v-if="templateForm.templateType === 'otr'">{{ $t('tenancy.rentRm') }}<input v-model.trim="templateForm.fields.advanceRental"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.agreementDate') }}<input v-model.trim="templateForm.fields.agreementDate" type="date"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.rentRm') }}<input v-model.trim="templateForm.fields.monthlyRent"></label>
          <label v-if="templateForm.templateType === 'otr'">{{ $t('tenancy.leaseStartDate') }}<input v-model.trim="templateForm.fields.commencementDate" type="date"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.leaseStartDate') }}<input v-model.trim="templateForm.fields.leaseStart" type="date"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.leaseEndDate') }}<input v-model.trim="templateForm.fields.leaseEnd" type="date"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.leaseYears') }}<input v-model.trim="templateForm.fields.termYears"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.paymentDay') }}<input v-model.trim="templateForm.fields.paymentDay" type="number" min="1" max="31"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.advanceRental') }}<input v-model.trim="templateForm.fields.advanceRental"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.securityDeposit') }}<input v-model.trim="templateForm.fields.securityDeposit"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.utilityDeposit') }}<input v-model.trim="templateForm.fields.utilityDeposit"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.bankName') }}<input v-model.trim="templateForm.fields.bankName"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.bankAccount') }}<input v-model.trim="templateForm.fields.bankAccount"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.bankBranch') }}<input v-model.trim="templateForm.fields.bankBranch"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.renewalOption') }}<input v-model.trim="templateForm.fields.renewalOption"></label>
          <label v-if="templateForm.templateType === 'tenancy-agreement'">{{ $t('tenancy.useOfPremises') }}<input v-model.trim="templateForm.fields.use"></label>
          <label v-if="templateForm.templateType === 'otr'">{{ $t('tenancy.leaseYears') }}<input v-model.trim="templateForm.fields.periodYears"></label>
          <label v-if="templateForm.templateType === 'otr'">{{ $t('tenancy.depositMonths') }}<input v-model.trim="templateForm.fields.securityDepositMonths"></label>
          <label v-if="templateForm.templateType === 'otr'">{{ $t('tenancy.depositRm') }}<input v-model.trim="templateForm.fields.securityDeposit"></label>
          <label v-if="templateForm.templateType === 'otr'">{{ $t('tenancy.utilityDepositMonths') }}<input v-model.trim="templateForm.fields.utilityDepositMonths"></label>
          <label v-if="templateForm.templateType === 'otr'">{{ $t('tenancy.utilityDepositRm') }}<input v-model.trim="templateForm.fields.utilityDeposit"></label>
          <label v-if="templateForm.templateType === 'otr'">{{ $t('tenancy.stampingFeesRm') }}<input v-model.trim="templateForm.fields.stampingFee"></label>
          <label v-if="templateForm.templateType === 'otr'">{{ $t('tenancy.totalBeforeKeysRm') }}<input v-model.trim="templateForm.fields.totalBeforeKeys"></label>
          <label>{{ $t('tenancy.earnestDepositRm') }}<input v-model.trim="templateForm.fields.earnestDeposit"></label>
          <label class="wide">{{ templateForm.templateType === 'tenancy-agreement' ? $t('tenancy.specialConditions') : $t('tenancy.otherConditions') }}<input v-model.trim="templateForm.fields[templateForm.templateType === 'tenancy-agreement' ? 'specialConditions' : 'otherConditions']"></label>
          <p v-if="templateError" class="admin-property-error">{{ templateError }}</p>
        </div>
        <menu><button type="button" @click="closeDialog('templateDialog')">{{ $t('tenancy.cancel') }}</button><button class="primary-btn" :disabled="templateBusy">{{ templateBusy ? $t('tenancy.generating') : (templateForm.signingMode ? $t('tenancy.generateContinueSigning') : $t('tenancy.generateDownloadPdf')) }}</button></menu>
      </form>
    </dialog>
    <dialog ref="leaseSigningDialog" class="modal admin-tenancy-dialog"><form method="dialog" @submit.prevent="startLeaseSigning"><div class="modal-head"><div><h3>{{ $t('legacy.t_d533a7b75659') }}</h3><small>{{ $t('legacy.t_a97de7d266eb') }}</small></div><button type="button" class="icon-close" @click="closeDialog('leaseSigningDialog')">×</button></div><div class="form-grid tenancy-form"><label>{{ $t('legacy.t_a6c87526ef43') }}<input v-model.trim="signatureForm.signerName" required maxlength="190"></label><label>{{ $t('legacy.t_7659e49d822a') }}<input v-model.trim="signatureForm.signerEmail" required type="email" maxlength="190"></label><label>{{ $t('legacy.t_1f156a7776ee') }}<input v-model.number="signatureForm.expiresInDays" required type="number" min="1" max="30"></label><p v-if="actionError" class="admin-property-error">{{ actionError }}</p></div><menu><button type="button" @click="closeDialog('leaseSigningDialog')">{{ $t('legacy.t_4d0b4688c787') }}</button><button class="primary-btn" :disabled="signatureBusy">{{ signatureBusy ? $t('legacy.t_45c36a4dc86c') : $t('legacy.t_65197f94b6e2') }}</button></menu></form></dialog>

  </section>
</template>

<script>
import { createAdminLease, createAdminTenant, fetchAdminLeaseContract, fetchAdminLeaseRentInvoices, fetchAdminTenancy, fetchAdminTenancyOptions, generateAdminContractTemplate, sendAdminRentReminder, startAdminLeaseSignature, transferAdminLease, updateAdminLease, uploadAdminLeaseContract } from '../services/propertyApi';
const today = () => new Date().toISOString().slice(0, 10);
const nextYear = () => { const date = new Date(); date.setFullYear(date.getFullYear() + 1); return date.toISOString().slice(0, 10); };
const plusDays = (value, days) => { const date = new Date(`${value}T00:00:00`); date.setDate(date.getDate() + days); return date.toISOString().slice(0, 10); };
export default {
  inject: ['page'],
  data() { return { rows: [], selectedId: null, selectedLeaseId: null, selectedInvoiceId: null, invoiceDetails: [], invoiceDetailsLoading: false, invoiceDetailsError: '', invoiceDetailTitle: '', totalRows: 0, totalPages: 1, pageNumber: 1, pageSize: 10, loading: false, errorMessage: '', saving: false, contractBusy: false, signatureBusy: false, templateBusy: false, templateError: '', templateForm: { templateType: 'otr', signingMode: false, fields: {} }, signatureForm: { signerName: '', signerEmail: '', expiresInDays: 7 }, leaseContractFile: null, transferContractFile: null, actionError: '', requestSerial: 0, todayDate: today(), options: { projects: [], tenants: [], units: [] }, tenantForm: { fullName: '', identityNo: '', phone: '', email: '', status: 'active' }, leaseForm: { tenantId: null, unitId: null, rentalMandateId: null, startDate: today(), endDate: nextYear(), monthlyRent: 0, depositAmount: 0, paymentDay: 1, rentCalculationMethod: 'monthly' }, editLeaseForm: { startDate: '', endDate: '', monthlyRent: 0, depositAmount: 0, paymentDay: 1, rentCalculationMethod: 'monthly' }, transferLeaseForm: { newTenantId: null, transferDate: today(), endDate: '', monthlyRent: 0, depositAmount: 0, paymentDay: 1, rentCalculationMethod: 'monthly' } }; },
  computed: {
    selectedRow() { return this.rows.find(row => row.leaseId && row.leaseId === this.selectedLeaseId) || this.rows.find(row => !row.leaseId && row.tenantId === this.selectedId) || this.rows[0] || null; },
    visiblePages() { const start = Math.max(1, Math.min(this.pageNumber - 2, this.totalPages - 4)); return Array.from({ length: Math.min(5, this.totalPages) }, (_, i) => start + i); },
    rentProgress() { return !Number(this.selectedRow?.amountDue) ? 0 : Math.min(100, Math.round(Number(this.selectedRow.amountPaid || 0) / Number(this.selectedRow.amountDue) * 100)); },
    tenantNonce() { return this.page.adminTenantCreateNonce; }, leaseNonce() { return this.page.adminLeaseCreateNonce; },
    transferTenantOptions() { return (this.options.tenants || []).filter(tenant => tenant.id !== this.selectedRow?.tenantId); },
    selectedLeaseUnit() { return (this.options.units || []).find(unit => unit.id === this.leaseForm.unitId) || null; },
    transferMinDate() { if (!this.selectedRow?.leaseStart) return this.todayDate; return [this.todayDate, plusDays(this.selectedRow.leaseStart, 1)].sort().at(-1); }
  },
  watch: {
    'page.moduleSearch'() { this.resetLoad(); }, 'page.globalSearch'() { this.resetLoad(); }, 'page.projectFilter'() { this.resetLoad(); }, 'page.statusFilter'() { this.resetLoad(); }, 'page.dateStart'() { this.resetLoad(); }, 'page.dateEnd'() { this.resetLoad(); },
    pageSize() { this.pageNumber = 1; this.loadData(); }, tenantNonce(v, old) { if (v > old) this.openTenant(); }, leaseNonce(v, old) { if (v > old) this.openLease(); },
    rows: { deep: true, handler(rows) { const current = rows.find(row => row.leaseId && row.leaseId === this.selectedLeaseId) || rows.find(row => !row.leaseId && row.tenantId === this.selectedId) || rows[0] || null; this.selectedId = current?.tenantId || null; this.selectedLeaseId = current?.leaseId || null; this.selectedInvoiceId = current?.invoiceId || null; } }
  },
   mounted() { this.page.projectFilter = '全部建案'; this.page.statusFilter = '全部狀態'; this.loadData().then(() => this.applyProcessRoute()); },
  methods: {
     async applyProcessRoute() { const params = new URLSearchParams(window.location.search); const workflow = params.get('workflow'); const unitId = params.get('unitId'); if (workflow === 'tenant-create') { this.openTenant(); return; } if (workflow === 'lease-create') { this.openLease(); if (unitId) { this.leaseForm.unitId = Number(unitId); this.leaseForm.rentalMandateId = params.get('mandateId') ? Number(params.get('mandateId')) : null; this.applyMandateDates(); } return; } const row = this.rows.find(item => String(item.unitId) === String(unitId)); if (!row) return; this.selectRow(row); if (workflow === 'otr') this.openTemplateGenerator('otr'); if (workflow === 'lease-contract') this.openTemplateGenerator('tenancy-agreement', true); if (workflow === 'invoice') await this.openInvoiceDetails(row); },
     async loadData() { const serial = ++this.requestSerial; this.loading = true; this.errorMessage = ''; try { const [response, options] = await Promise.all([fetchAdminTenancy({ page: this.pageNumber, pageSize: this.pageSize, keyword: this.page.globalSearch || this.page.moduleSearch || '', projectName: String(this.page.projectFilter || '').includes('全部') ? '' : this.page.projectFilter, status: this.statusParam(this.page.statusFilter), startDate: this.page.dateStart, endDate: this.page.dateEnd }), fetchAdminTenancyOptions()]); if (serial !== this.requestSerial) return; this.rows = response.rows || []; this.totalRows = response.page?.totalRows || 0; this.totalPages = response.page?.totalPages || 1; this.pageNumber = response.page?.page || 1; this.options = options || { projects: [], tenants: [], units: [] }; this.page.adminTenancyProjects = this.options.projects || []; this.page.adminTenancyMetrics = this.metrics(response.summary || {}); this.page.adminTenancyExportHeaders = ['租客', '建案', '單位', '租約編號', '租期開始', '租期結束', '月租', '帳單月份', '本期應收', '已收', '未收', '租金狀態']; this.page.adminTenancyExportRows = this.rows.map(row => [row.tenantName, row.projectName || '', row.unitNo || '', row.leaseNo || '', row.leaseStart || '', row.leaseEnd || '', row.monthlyRent, row.billingMonth || '', row.amountDue, row.amountPaid, row.amountUnpaid, this.rentLabel(row.rentStatus)]); } catch (e) { if (serial !== this.requestSerial) return; this.rows = []; this.errorMessage = e.message || 'API request failed'; this.page.adminTenancyMetrics = null; this.page.adminTenancyExportRows = []; } finally { if (serial === this.requestSerial) this.loading = false; } },
    metrics(s) { const t = (key, params) => this.$t(`tenancy.${key}`, params); return [{ icon: '租', label: t('totalTenants'), value: t('tenantCountValue', { count: Number(s.tenantCount || 0) }), delta: t('activeLeaseValue', { count: Number(s.activeLeaseCount || 0) }), trend: 'up' }, { icon: '款', label: t('currentDueRent'), value: this.money(s.currentDue), delta: t('liveCalculation'), trend: 'up' }, { icon: '✓', label: t('currentPaidRent'), value: this.money(s.currentPaid), delta: t('postedCollections'), trend: 'up' }, { icon: '!', label: t('currentUnpaidAmount'), value: this.money(s.currentUnpaid), delta: t('needsFollowUp'), trend: Number(s.currentUnpaid) ? 'down' : 'up' }, { icon: '餘', label: t('totalUnpaidAmount'), value: this.money(s.totalUnpaid), delta: t('pastMonthsIncluded'), trend: Number(s.totalUnpaid) ? 'down' : 'up' }, { icon: '部', label: t('partialPaymentCount'), value: t('countValue', { count: Number(s.partialCount || 0) }), delta: t('currentMonthBills'), trend: Number(s.partialCount) ? 'down' : '' }, { icon: '逾', label: t('overdueRentCount'), value: t('countValue', { count: Number(s.overdueCount || 0) }), delta: t('currentMonthBills'), trend: Number(s.overdueCount) ? 'down' : 'up' }]; },
    resetLoad() { this.pageNumber = 1; this.loadData(); }, goPage(n) { if (n >= 1 && n <= this.totalPages && n !== this.pageNumber) { this.pageNumber = n; this.loadData(); } },
    openTenant() { this.tenantForm = { fullName: '', identityNo: '', phone: '', email: '', status: 'active' }; this.actionError = ''; this.$refs.tenantDialog?.showModal(); },
    openLease() { this.leaseForm = { tenantId: this.selectedRow?.tenantId || null, unitId: null, rentalMandateId: null, startDate: today(), endDate: nextYear(), monthlyRent: 0, depositAmount: 0, paymentDay: 1, rentCalculationMethod: 'daily_prorated' }; this.leaseContractFile = null; this.actionError = ''; this.$refs.leaseDialog?.showModal(); },
    applyMandateDates() { const unit = this.selectedLeaseUnit; if (!unit) return; this.leaseForm.startDate = unit.mandateStartDate || today(); this.leaseForm.endDate = unit.mandateEndDate || nextYear(); },
    closeDialog(ref) { this.$refs[ref]?.close(); this.actionError = ''; },
    async submitTenant() { this.saving = true; this.actionError = ''; try { await createAdminTenant(this.tenantForm); this.closeDialog('tenantDialog'); await this.loadData(); this.page.showToast('租客已建立'); } catch (e) { this.actionError = e.message || '建立租客失敗'; } finally { this.saving = false; } },
    async submitLease() { this.saving = true; this.actionError = ''; try { const created = await createAdminLease({ ...this.leaseForm, rentCalculationMethod: 'daily_prorated' }); this.selectedId = this.leaseForm.tenantId; this.selectedLeaseId = created.id; this.selectedInvoiceId = null; if (this.leaseContractFile) { try { await uploadAdminLeaseContract(created.id, this.leaseContractFile); } catch (uploadError) { this.closeDialog('leaseDialog'); await this.loadData(); this.page.showToast(`租約已建立，但文件上傳失敗：${uploadError.message}`); return; } } this.closeDialog('leaseDialog'); await this.loadData(); this.page.showToast(this.leaseContractFile ? '租約、文件與截至本月帳單已建立' : '租約與截至本月帳單已建立'); } catch (e) { this.actionError = e.message || '建立租約失敗'; } finally { this.saving = false; } },
    openEditLease() { if (!this.selectedRow?.leaseId || this.selectedRow.leaseStatus !== 'active') return; this.editLeaseForm = { startDate: this.selectedRow.leaseStart, endDate: this.selectedRow.leaseEnd, monthlyRent: Number(this.selectedRow.monthlyRent), depositAmount: Number(this.selectedRow.depositAmount), paymentDay: Number(this.selectedRow.paymentDay), rentCalculationMethod: 'daily_prorated' }; this.actionError = ''; this.$refs.editLeaseDialog?.showModal(); },
    async submitEditLease() { this.saving = true; this.actionError = ''; try { await updateAdminLease(this.selectedRow.leaseId, { ...this.editLeaseForm, rentCalculationMethod: 'daily_prorated' }); this.closeDialog('editLeaseDialog'); await this.loadData(); this.page.showToast('租約資料已更新'); } catch (e) { this.actionError = e.message || '租約修改失敗'; } finally { this.saving = false; } },
    openTransferLease() { if (!this.selectedRow?.leaseId || this.selectedRow.leaseStatus !== 'active') return; this.transferLeaseForm = { newTenantId: null, transferDate: this.transferMinDate, endDate: this.selectedRow.leaseEnd, monthlyRent: Number(this.selectedRow.monthlyRent), depositAmount: Number(this.selectedRow.depositAmount), paymentDay: Number(this.selectedRow.paymentDay), rentCalculationMethod: 'daily_prorated' }; this.transferContractFile = null; this.actionError = ''; this.$refs.transferLeaseDialog?.showModal(); },
    selectTransferContract(event) { const file = event.target.files?.[0] || null; if (file && !this.validContract(file)) { event.target.value = ''; return; } this.transferContractFile = file; },
    async submitTransferLease() { this.saving = true; this.actionError = ''; try { const oldLeaseId = this.selectedRow.leaseId; const newTenantId = this.transferLeaseForm.newTenantId; const created = await transferAdminLease(oldLeaseId, { ...this.transferLeaseForm, rentCalculationMethod: 'daily_prorated' }); this.selectedId = newTenantId; this.selectedLeaseId = created.id; this.selectedInvoiceId = null; if (this.transferContractFile) { try { await uploadAdminLeaseContract(created.id, this.transferContractFile); } catch (uploadError) { this.closeDialog('transferLeaseDialog'); await this.loadData(); this.page.showToast(`轉租已完成，但新租約文件上傳失敗：${uploadError.message}`); return; } } this.closeDialog('transferLeaseDialog'); await this.loadData(); this.page.showToast(this.transferContractFile ? '轉租及新租約文件已完成' : '轉租已完成'); } catch (e) { this.actionError = e.message || '轉租失敗'; } finally { this.saving = false; } },
    selectNewLeaseContract(event) { const file = event.target.files?.[0] || null; if (file && !this.validContract(file)) { event.target.value = ''; return; } this.leaseContractFile = file; },
    chooseContract() { if (!this.selectedRow?.leaseId || this.contractBusy) return; this.$refs.contractInput.value = ''; this.$refs.contractInput.click(); },
    async uploadSelectedContract(event) { const file = event.target.files?.[0]; if (!file || !this.validContract(file)) return; const replacing = Boolean(this.selectedRow?.contractDocumentId); this.contractBusy = true; try { await uploadAdminLeaseContract(this.selectedRow.leaseId, file); await this.loadData(); this.page.showToast(replacing ? '租約文件已更換' : '租約文件已上傳'); } catch (e) { this.page.showToast(e.message || '租約文件上傳失敗'); } finally { this.contractBusy = false; event.target.value = ''; } },
    async viewContract() { await this.openContract(false); },
    async downloadContract() { await this.openContract(true); },
    openLeaseSigning() { if (!this.selectedRow?.leaseId || this.selectedRow.contractSigned || this.selectedRow.contractStatus === 'signed') return; this.openTemplateGenerator('tenancy-agreement', true); },
    openLeaseSigningDialog() { this.signatureForm = { signerName: this.selectedRow?.tenantName || '', signerEmail: this.selectedRow?.email || '', expiresInDays: 7 }; this.actionError = ''; this.$refs.leaseSigningDialog?.showModal(); },
    async startLeaseSigning() { this.signatureBusy = true; this.actionError = ''; try { await startAdminLeaseSignature(this.selectedRow.leaseId, this.signatureForm); this.closeDialog('leaseSigningDialog'); this.page.showToast('簽署邀請已寄出'); } catch (e) { this.actionError = e.message || '簽署邀請寄送失敗'; } finally { this.signatureBusy = false; } },
    openTemplateGenerator(type, signingMode = false) {
      const row = this.selectedRow;
      if (!row?.leaseId || !['otr', 'tenancy-agreement'].includes(type)) return;
      const propertyAddress = `${row.projectName || ''} ${row.unitNo || ''}`.trim();
      const years = row.leaseStart && row.leaseEnd
        ? String(Math.max(1, Math.round((new Date(row.leaseEnd) - new Date(row.leaseStart)) / (365 * 86400000)))) : '1';
      const common = {
        caseNo: row.leaseNo || `LEASE-${row.leaseId}`,
        propertyAddress,
        landlordName: row.ownerName || '', landlordIdentity: row.ownerIdentity || '',
        tenantName: row.tenantName || '', tenantIdentity: row.identityNo || '',
        monthlyRent: row.monthlyRent ? this.money(row.monthlyRent) : '',
        advanceRental: row.monthlyRent ? this.money(row.monthlyRent) : '',
        securityDeposit: row.depositAmount ? this.money(row.depositAmount) : '',
        utilityDeposit: '', otherConditions: '', specialConditions: '',
        commencementDate: row.leaseStart || '', periodYears: years,
        securityDepositMonths: '', utilityDepositMonths: '', stampingFee: '', totalBeforeKeys: '',
        earnestDeposit: '', commission: '', startDate: row.leaseStart || this.todayDate
      };
      const fields = type === 'tenancy-agreement' ? {
        ...common, leaseId: row.leaseId || '', unitNo: row.unitNo || '', agreementDate: this.todayDate,
        landlordAddress: row.ownerAddress || '', tenantPhone: row.phone || '',
        tenantAddress: row.tenantAddress || '', tenantEmail: row.email || '',
        leaseStart: row.leaseStart || '', leaseEnd: row.leaseEnd || '',
        termYears: years, paymentDay: row.paymentDay || 1,
         use: 'For Residential use only', bankName: '', bankAccount: '', bankBranch: '', renewalOption: ''
      } : common;
      this.templateForm = { templateType: type, signingMode, fields };
      this.templateError = '';
      this.$refs.templateDialog?.showModal();
    },
    async generateTemplate() {
      this.templateBusy = true;
      this.templateError = '';
      try {
        const mode = this.templateForm.signingMode;
        const result = await generateAdminContractTemplate(this.templateForm.templateType, this.templateForm.fields);
        if (mode) {
          const file = new File([result.blob], result.filename, { type: 'application/pdf' });
          await uploadAdminLeaseContract(this.selectedRow.leaseId, file);
          await this.loadData();
          this.closeDialog('templateDialog');
          this.page.showToast(this.$t('tenancy.contractReadyForSigning'));
          this.openLeaseSigningDialog();
        } else {
          const url = URL.createObjectURL(result.blob);
          const link = document.createElement('a'); link.href = url; link.download = result.filename; link.style.display = 'none';
          document.body.appendChild(link); link.click(); link.remove();
          setTimeout(() => URL.revokeObjectURL(url), 1000);
          this.closeDialog('templateDialog');
          this.page.showToast(this.templateForm.templateType === 'tenancy-agreement'
            ? this.$t('tenancy.tenancyTemplateGenerated') : this.$t('tenancy.templateGenerated'));
        }
      } catch (e) {
        this.templateError = e.message || this.$t('tenancy.templateGenerateFailed');
      } finally { this.templateBusy = false; }
    },
    async openContract(download) { if (!this.selectedRow?.leaseId) return; this.contractBusy = true; try { const result = await fetchAdminLeaseContract(this.selectedRow.leaseId, download); const url = URL.createObjectURL(result.blob); if (download) { const link = document.createElement('a'); link.href = url; link.download = this.selectedRow.contractDocumentName || `lease-contract-${this.selectedRow.leaseId}`; link.click(); URL.revokeObjectURL(url); } else { window.open(url, '_blank', 'noopener'); setTimeout(() => URL.revokeObjectURL(url), 60000); } } catch (e) { this.page.showToast(e.message || (download ? '租約下載失敗' : '租約預覽失敗')); } finally { this.contractBusy = false; } },
    validContract(file) { const types = ['application/pdf', 'image/jpeg', 'image/png']; if (!types.includes(file.type) || file.size > 10 * 1024 * 1024) { this.page.showToast('只支援 10MB 以內的 PDF、JPG 或 PNG 租約文件'); return false; } return true; },
    selectRow(row) { this.selectedId = row?.tenantId || null; this.selectedLeaseId = row?.leaseId || null; this.selectedInvoiceId = row?.invoiceId || null; },
    async openInvoiceDetails(row) { if (!row?.leaseId) return; this.selectRow(row); this.invoiceDetailTitle = `${row.tenantName || '租客'} · ${row.projectName || ''} ${row.unitNo || ''}`.trim(); this.invoiceDetails = []; this.invoiceDetailsError = ''; this.invoiceDetailsLoading = true; this.$refs.invoiceDetailsDialog?.showModal(); try { this.invoiceDetails = await fetchAdminLeaseRentInvoices(row.leaseId); } catch (e) { this.invoiceDetailsError = e.message || '租金明細載入失敗'; } finally { this.invoiceDetailsLoading = false; } },
    async sendReminder() { try { await sendAdminRentReminder(this.selectedRow.invoiceId); this.page.showToast('租金提醒已建立'); } catch (e) { this.page.showToast(e.message || '提醒建立失敗'); } },
    statusParam(v) { return ({ '已收': 'paid', '部分收款': 'partial', '待收': 'unpaid', '逾期': 'overdue' })[v] || ''; },
    contractStatusLabel(v) { return ({ missing: '未上傳', uploaded: '已上傳待簽署', pending: '簽署中', signed: '已簽署生效' })[v] || '未上傳'; },
    rentLabel(v) { return ({ paid: '已收', partial: '部分收款', unpaid: '待收', overdue: '逾期', no_invoice: '未出帳' })[v] || '未出帳'; },
    rentClass(v) { return v === 'paid' ? 'green' : v === 'overdue' ? 'red' : v === 'partial' || v === 'unpaid' ? 'orange' : 'gray'; },
    money(v) { return `RM ${Number(v || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }, initials(name) { return String(name || '').split(/\s+/).slice(0, 2).map(p => p[0]).join('').toUpperCase() || '租'; }
  }
};
</script>

<style scoped>
.lease-change-note,.lease-transfer-warning{grid-column:1/-1;display:grid;gap:5px;padding:11px 13px;border:1px solid #d9e3ed;border-radius:8px;background:#f6f9fc;color:#53667b;font-size:12px}.lease-change-note b{color:#12375f}.lease-transfer-warning{border-color:#efd28b;background:#fff8e7;color:#78570a}.lease-transfer-warning b{color:#8b5d00}.tenancy-actions button:first-child{background:#0b376c;color:#fff;border-color:#0b376c}.tenancy-actions button:disabled{opacity:.5;cursor:not-allowed}.tenancy-table-wrap th:last-child,.tenancy-table-wrap td:last-child{width:58px;min-width:58px;padding:8px 6px;text-align:center}.tenancy-detail-button{width:30px;height:30px;border:1px solid #cbdced;border-radius:7px;background:#fff;color:#17558d;transition:.16s}.tenancy-detail-button:hover:not(:disabled){border-color:#8db4d4;background:#eef6fd;color:#0a3f70;transform:translateY(-1px)}.tenancy-detail-button:disabled{opacity:.42;cursor:not-allowed}.tenancy-detail-icon{width:16px;height:16px;fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:1.8}
.contract-template-dialog{width:min(760px,96vw)}
</style>
