<template>
  <section class="content-grid admin-finance-workspace admin-rent-finance-workspace">
    <div class="panel table-panel finance-review-list-panel">
      <div class="panel-head"><div><h2>{{ $t('legacy.t_9d616b1af2c5') }}</h2><span>{{ totalRows }} {{ $t('legacy.t_d1c700a3bcad') }}</span></div><div class="history-actions"><span v-if="selectedRow" class="selected-transaction">{{ $t('legacy.t_cca56d30f473') }}{{ selectedRow.transactionNo }}</span><span v-else class="selected-transaction empty">{{ $t('legacy.t_d67bddbb5554') }}</span><button class="primary-btn" :disabled="!selectedRow || proofBusy" @click="chooseProof">{{ selectedRow?.proofDocumentId ? $t('legacy.t_7c9e4cb66071') : $t('legacy.t_0531fc112506') }}</button><a v-if="selectedRow" class="receipt-btn" :href="receiptUrl(selectedRow)" download>{{ $t('legacy.t_4900e8f9eaa8') }}</a><button v-else class="receipt-btn" disabled>{{ $t('legacy.t_4900e8f9eaa8') }}</button></div></div>
      <div class="rent-history-filters"><label>{{ $t('legacy.t_a7ff541f4978') }}<input v-model="historyMonth" type="month"></label><label>{{ $t('legacy.t_42c950a2ce7c') }}<input v-model.trim="tenantFilter" :placeholder="$t('legacy.t_76dc13e8d8c0')"></label><label>{{ $t('legacy.t_4ce0ee8cc0b2') }}<input v-model.trim="unitFilter" :placeholder="$t('legacy.t_0049e42d5032')"></label><button @click="clearHistoryFilters">{{ $t('legacy.t_bdc000aa0264') }}</button></div>
      <input ref="proofInput" type="file" accept="application/pdf,image/jpeg,image/png" style="display:none" @change="uploadSelectedProof">
      <div v-if="errorMessage" class="admin-owner-state error"><strong>{{ $t('legacy.t_71b962d15d98') }}</strong><span>{{ errorMessage }}</span><button @click="loadData">{{ $t('legacy.t_0c9157b5bfac') }}</button></div>
      <div v-else class="table-wrap finance-review-table-wrap">
        <table>
          <thead><tr><th>{{ $t('legacy.t_32e88cf956f6') }}</th><th>{{ $t('legacy.t_42c950a2ce7c') }}</th><th>{{ $t('legacy.t_114246450ff0') }}</th><th>{{ $t('legacy.t_a7ff541f4978') }}</th><th>{{ $t('legacy.t_b35a920fa6f3') }}</th><th>{{ $t('legacy.t_9afa4ce0531c') }}</th><th>{{ $t('legacy.t_41ee43593eb7') }}</th><th>{{ $t('legacy.t_4feb65fa9683') }}</th><th>{{ $t('legacy.t_94007fdd6e4e') }}</th><th>{{ $t('legacy.t_f3ea6d345e2a') }}</th></tr></thead>
          <tbody>
            <tr v-for="row in rows" :key="row.id" :class="{ selected: row.id === selectedRow?.id }" @click="selectRow(row)">
              <td><strong>{{ row.transactionNo }}</strong><small>{{ paymentMethodLabel(row.paymentMethod) }}</small></td>
              <td>{{ row.tenantName }}<small>{{ row.leaseNo }}</small></td>
              <td>{{ row.projectName }}<small>{{ row.unitNo }}</small></td>
              <td>{{ monthLabel(row.billingMonth) }}<small>{{ $t('legacy.t_8066e0f41f1f') }} {{ row.dueDate || '—' }}</small></td>
              <td><b>{{ row.currency || 'MYR' }} {{ money(row.amount) }}</b></td>
              <td>{{ row.transactionDate || '—' }}</td>
              <td><button class="finance-proof-link" :class="{ missing: !row.proofDocumentId }" @click.stop="proofAction(row)">{{ row.proofDocumentId ? $t('legacy.t_96bd7ca72147') : $t('legacy.t_0531fc112506') }}</button><span v-if="viewMode === 'history'" class="finance-document-actions"><a class="finance-proof-link receipt-link" :href="documentUrl(row, 'invoice')" download @click.stop>Invoice / 发票</a><a class="finance-proof-link receipt-link" :href="documentUrl(row, 'receipt')" download @click.stop>Official Receipt / 收据</a></span></td>
              <td><span class="tag" :class="confirmationClass(row.confirmationStatus)">{{ confirmationLabel(row.confirmationStatus) }}</span></td>
              <td><span class="tag" :class="syncClass(row.syncStatus)">{{ syncLabel(row.syncStatus) }}</span></td>
              <td><button class="row-actions" @click.stop="selectRow(row)">…</button></td>
            </tr>
            <tr v-if="!loading && !rows.length"><td colspan="10" class="admin-owner-empty">{{ $t('legacy.t_127791a5adcf') }}</td></tr>
          </tbody>
        </table>
      </div>
      <div class="pager"><span>{{ $t('legacy.t_3b6ef811b85a') }} {{ totalRows }} {{ $t('legacy.t_86761b63a7bd') }}</span><div class="admin-building-pager"><button :disabled="pageNumber <= 1" @click="goPage(pageNumber - 1)">&lt;</button><button v-for="n in visiblePages" :key="n" :class="{ active: n === pageNumber }" @click="goPage(n)">{{ n }}</button><button :disabled="pageNumber >= totalPages" @click="goPage(pageNumber + 1)">&gt;</button><select v-model.number="pageSize"><option :value="10">{{ $t('legacy.t_fc6da0e815a1') }}</option><option :value="20">{{ $t('legacy.t_93d673672fa5') }}</option><option :value="50">{{ $t('legacy.t_529930b886d2') }}</option></select></div></div>
    </div>

    <aside class="panel detail-panel finance-review-detail">
      <div v-if="selectedRow" class="detail-card">
        <div class="profile finance-review-profile"><div class="big-avatar">{{ $t('legacy.t_5d00753a306a') }}</div><div class="finance-review-profile-copy"><h3>{{ selectedRow.transactionNo }}</h3><p>{{ selectedRow.tenantName }} · {{ selectedRow.projectName }} / {{ selectedRow.unitNo }}</p></div><span class="tag" :class="confirmationClass(selectedRow.confirmationStatus)">{{ confirmationLabel(selectedRow.confirmationStatus) }}</span></div>
        <div class="detail-actions finance-review-actions">
          <button v-if="selectedRow.proofDocumentId" :disabled="proofBusy" @click="openProof">{{ $t('legacy.t_16194d3fdaa8') }}</button>
          <button v-if="selectedRow.proofDocumentId" :disabled="proofBusy" @click="downloadProof">{{ $t('legacy.t_160323396007') }}</button>
          <button v-if="selectedRow.receiptNo" :disabled="receiptBusy" @click="downloadReceipt">{{ $t('legacy.t_4900e8f9eaa8') }}</button>
          <a v-if="viewMode === 'history'" class="finance-document-button" :href="documentUrl(selectedRow, 'invoice')" download>Invoice / 发票</a>
          <a v-if="viewMode === 'history'" class="finance-document-button" :href="documentUrl(selectedRow, 'receipt')" download>Official Receipt / 收据</a>
          <button :disabled="proofBusy" @click="chooseProof">{{ proofBusy ? $t('legacy.t_1e038f9b55ec') : selectedRow.proofDocumentId ? $t('legacy.t_7c9e4cb66071') : $t('legacy.t_0531fc112506') }}</button>
          <button @click="goToTenancy">{{ $t('legacy.t_bcdce2d6efbe') }}</button>
        </div>
        <div class="detail-section"><h4><span class="num">{{ $t('legacy.t_356a192b7913') }}</span>{{ $t('legacy.t_ce17f11e7211') }}</h4><div class="kv"><span>{{ $t('legacy.t_42c950a2ce7c') }}</span><b>{{ selectedRow.tenantName }}</b></div><div class="kv"><span>{{ $t('legacy.t_c6b9a8cfdb21') }}</span><b>{{ paymentMethodLabel(selectedRow.paymentMethod) }}</b></div><div class="kv"><span>{{ $t('legacy.t_9afa4ce0531c') }}</span><b>{{ selectedRow.transactionDate || '—' }}</b></div><div class="kv"><span>{{ $t('legacy.t_b35a920fa6f3') }}</span><b>{{ selectedRow.currency || 'MYR' }} {{ money(selectedRow.amount) }}</b></div></div>
        <div class="detail-section"><h4><span class="num">{{ $t('legacy.t_da4b9237bacc') }}</span>{{ $t('legacy.t_2e5d38a2bd27') }}</h4><div class="kv"><span>{{ $t('legacy.t_bd95f007d6d0') }}</span><b>{{ selectedRow.leaseNo }}</b></div><div class="kv"><span>{{ $t('legacy.t_a7ff541f4978') }}</span><b>{{ monthLabel(selectedRow.billingMonth) }}</b></div><div class="kv"><span>{{ $t('legacy.t_fdeda5befee2') }}</span><b>{{ $t('legacy.t_5e7b60c626a4') }} {{ money(selectedRow.invoiceAmount) }}</b></div><div class="kv"><span>{{ $t('legacy.t_109f4a1ff366') }}</span><b>{{ $t('legacy.t_5e7b60c626a4') }} {{ money(selectedRow.invoicePaid) }}</b></div><div class="progress"><i :style="{ width: invoiceProgress + '%' }"></i></div></div>
        <div class="detail-section"><h4><span class="num">{{ $t('legacy.t_77de68daecd8') }}</span>{{ $t('legacy.t_8048e4b28ff2') }}</h4><div class="kv"><span>{{ $t('legacy.t_b7aeb7e21fa3') }}</span><b>{{ selectedRow.proofName || $t('legacy.t_3c5b845dce11') }}</b></div><div class="kv"><span>{{ $t('legacy.t_2ad8b0b96fec') }}</span><b>{{ fileSize(selectedRow.proofSize) }}</b></div><div class="kv"><span>{{ $t('legacy.t_94007fdd6e4e') }}</span><b>{{ syncLabel(selectedRow.syncStatus) }}</b></div><div class="kv"><span>{{ $t('legacy.t_f3f199f6441e') }}</span><b>{{ formatDateTime(selectedRow.submittedAt) }}</b></div></div>
      </div>
      <div v-else class="admin-owner-empty">{{ $t('legacy.t_16c5e3b671a3') }}</div>
    </aside>

    <dialog ref="proofDialog" class="modal admin-finance-proof-dialog"><div class="modal-head"><div><h3>{{ $t('legacy.t_08ca85f55e3c') }}</h3><small>{{ selectedRow?.proofName || selectedRow?.transactionNo }}</small></div><button type="button" class="icon-close" @click="closeProof">×</button></div><div class="finance-proof-viewer"><div v-if="proofLoading" class="admin-owner-state">{{ $t('legacy.t_e526ed184e85') }}</div><img v-else-if="proofUrl && selectedRow?.proofMimeType?.startsWith('image/')" :src="proofUrl" :alt="$t('legacy.t_08ca85f55e3c')"><iframe v-else-if="proofUrl && selectedRow?.proofMimeType === 'application/pdf'" :src="proofUrl" :title="$t('legacy.t_b1c0f608af9c')"></iframe><div v-else class="admin-owner-state">{{ proofError || $t('legacy.t_410b7e2a33ff') }}</div></div><menu><button @click="closeProof">{{ $t('legacy.t_ddc05404b0d6') }}</button><button class="primary-btn" :disabled="!selectedRow?.proofDocumentId" @click="downloadProof">{{ $t('legacy.t_fb332e3c9ee6') }}</button></menu></dialog>
  </section>
</template>

<script>
import { downloadAdminFinanceDocuments, fetchAdminRentFinanceProjects, fetchAdminRentFinanceReviews, fetchAdminRentProof, getAdminFinanceDocumentUrl, getAdminRentReceiptUrl, uploadAdminRentProof } from '../services/propertyApi';

export default {
  inject: ['page'],
  data() { return { rows: [], selectedId: null, pageNumber: 1, pageSize: 10, totalRows: 0, totalPages: 1, loading: false, errorMessage: '', requestSerial: 0, proofBusy: false, receiptBusy: false, historyMonth: '', tenantFilter: '', unitFilter: '', proofLoading: false, proofError: '', proofUrl: '' }; },
  computed: {
    selectedRow() { return this.rows.find(row => row.id === this.selectedId) || null; },
    visiblePages() { const start = Math.max(1, Math.min(this.pageNumber - 2, this.totalPages - 4)); return Array.from({ length: Math.min(5, this.totalPages) }, (_, i) => start + i); },
    invoiceProgress() { return !Number(this.selectedRow?.invoiceAmount) ? 0 : Math.min(100, Math.round(Number(this.selectedRow.invoicePaid || 0) / Number(this.selectedRow.invoiceAmount) * 100)); },
    refreshNonce() { return this.page.adminFinanceRefreshNonce; },
    proofUploadNonce() { return this.page.adminRentProofUploadNonce; }
  },
  watch: {
    'page.moduleSearch'() { this.resetLoad(); }, 'page.globalSearch'() { this.resetLoad(); }, 'page.projectFilter'() { this.resetLoad(); }, 'page.statusFilter'() { this.resetLoad(); }, 'page.dateStart'() { this.resetLoad(); }, 'page.dateEnd'() { this.resetLoad(); }, historyMonth() { this.resetLoad(); }, tenantFilter() { this.resetLoad(); }, unitFilter() { this.resetLoad(); },
    pageSize() { this.pageNumber = 1; this.loadData(); }, refreshNonce(value, previous) { if (value > previous) this.loadData(); }, proofUploadNonce(value, previous) { if (value > previous) this.chooseProof(); }, rows: { deep: true, handler(rows) { if (!rows.some(row => row.id === this.selectedId)) this.selectedId = null; } }
  },
  mounted() { this.loadData(); }, beforeUnmount() { this.revokeProofUrl(); },
  methods: {
    async loadData() { const serial = ++this.requestSerial; const preferredId = this.selectedId; this.loading = true; this.errorMessage = ''; try { const [response, projects] = await Promise.all([fetchAdminRentFinanceReviews({ page: this.pageNumber, pageSize: this.pageSize, keyword: this.page.globalSearch || this.page.moduleSearch || '', projectName: String(this.page.projectFilter || '').includes('全部') ? '' : this.page.projectFilter, status: this.statusParam(this.page.statusFilter) || 'history', startDate: this.page.dateStart, endDate: this.page.dateEnd, billingMonth: this.historyMonth ? `${this.historyMonth}-01` : '', tenantName: this.tenantFilter, unitNo: this.unitFilter }), fetchAdminRentFinanceProjects()]); if (serial !== this.requestSerial) return; this.rows = response.rows || []; this.totalRows = response.page?.totalRows || 0; this.totalPages = response.page?.totalPages || 1; this.pageNumber = response.page?.page || 1; this.selectedId = this.rows.some(row => row.id === preferredId) ? preferredId : null; this.page.adminFinanceProjects = projects || []; this.page.adminFinanceMetrics = this.metrics(response.summary || {}); } catch (e) { if (serial !== this.requestSerial) return; this.rows = []; this.errorMessage = e.message || 'API request failed'; this.page.adminFinanceMetrics = null; } finally { if (serial === this.requestSerial) this.loading = false; } },
    metrics(s) { return [{ label: '租金收款記錄', value: `${Number(s.totalCount || 0)} 筆`, delta: `RM ${this.money(s.totalAmount)}`, trend: 'up' }, { label: '已上傳憑證', value: `${Number(s.withProofCount || 0)} 筆`, delta: '線下審批憑證', trend: 'up' }, { label: '缺少憑證', value: `${Number(s.missingProofCount || 0)} 筆`, delta: '需要補上文件', trend: Number(s.missingProofCount) ? 'down' : 'up' }, { label: '待同步 SQL', value: `${Number(s.pendingSyncCount || 0)} 筆`, delta: '會計同步狀態', trend: Number(s.pendingSyncCount) ? 'down' : 'up' }, { label: '本月收款金額', value: `RM ${this.money(s.monthAmount)}`, delta: '按收款日期統計', trend: 'up' }]; },
    resetLoad() { this.pageNumber = 1; this.loadData(); }, clearHistoryFilters() { this.historyMonth = ''; this.tenantFilter = ''; this.unitFilter = ''; }, goPage(n) { if (n >= 1 && n <= this.totalPages && n !== this.pageNumber) { this.pageNumber = n; this.loadData(); } }, selectRow(row) { this.selectedId = row.id; }, documentUrl(row, type) { return row?.id ? getAdminFinanceDocumentUrl(row.id, type) : '#'; }, async batchDownload(type) { const ids = this.rows.map(row => row.id).filter(Boolean); if (!ids.length) { this.page.showToast('当前没有可下载的历史记录'); return; } try { const result = await downloadAdminFinanceDocuments(ids, type); this.saveBlob(result.blob, result.filename); this.page.showToast(`已生成 ${ids.length} 份${type === 'invoice' ? '发票' : '收据'}`); } catch (error) { this.page.showToast(error.message || '批量下载失败'); } },
    proofAction(row) { this.selectRow(row); this.$nextTick(() => row.proofDocumentId ? this.openProof() : this.chooseProof()); }, chooseProof() { if (!this.selectedRow || this.proofBusy) return; this.$refs.proofInput.value = ''; this.$refs.proofInput.click(); },
    async uploadSelectedProof(event) { const file = event.target.files?.[0]; if (!file) return; if (!this.validProof(file)) { event.target.value = ''; return; } const replacing = Boolean(this.selectedRow.proofDocumentId); this.proofBusy = true; try { await uploadAdminRentProof(this.selectedRow.id, file); await this.loadData(); this.page.showToast(replacing ? '租金憑證已更換' : '租金憑證已補上'); } catch (e) { this.page.showToast(e.message || '租金憑證上傳失敗'); } finally { this.proofBusy = false; event.target.value = ''; } }, validProof(file) { if (!['application/pdf', 'image/jpeg', 'image/png'].includes(file.type) || file.size > 10 * 1024 * 1024) { this.page.showToast('只支援 10MB 以內的 PDF、JPG 或 PNG 憑證'); return false; } return true; },
     async openProof() { if (!this.selectedRow?.proofDocumentId) return; this.revokeProofUrl(); this.proofLoading = true; this.proofError = ''; this.$refs.proofDialog?.showModal(); try { const result = await fetchAdminRentProof(this.selectedRow.proofDocumentId); this.proofUrl = URL.createObjectURL(result.blob); } catch (e) { this.proofError = e.message || '租金付款憑證載入失敗'; } finally { this.proofLoading = false; } }, closeProof() { this.$refs.proofDialog?.close(); this.revokeProofUrl(); }, revokeProofUrl() { if (this.proofUrl) URL.revokeObjectURL(this.proofUrl); this.proofUrl = ''; }, async downloadProof() { try { const result = await fetchAdminRentProof(this.selectedRow.proofDocumentId, true); this.saveBlob(result.blob, this.selectedRow.proofName || `rent-proof-${this.selectedRow.id}`); } catch (e) { this.page.showToast(e.message || '租金付款憑證下載失敗'); } }, async downloadReceipt(row = this.selectedRow) { if (!row?.id || this.receiptBusy) return; this.receiptBusy = true; try { window.location.assign(getAdminRentReceiptUrl(row.id)); this.page.showToast('租金收據下載已開始'); } catch (e) { this.page.showToast(e.message || '租金收據下載失敗'); } finally { this.receiptBusy = false; } }, saveBlob(blob, fileName) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = fileName; link.style.display = 'none'; document.body.appendChild(link); link.click(); window.setTimeout(() => { link.remove(); URL.revokeObjectURL(url); }, 1000); },
    goToTenancy() { const keyword = this.selectedRow?.tenantName || this.selectedRow?.unitNo || ''; this.page.selectModule('adminTenants'); this.$nextTick(() => { this.page.globalSearch = keyword; }); }, receiptUrl(row) { return row?.id ? getAdminRentReceiptUrl(row.id) : '#'; }, statusParam(v) { return ({ '已確認': 'confirmed', '已退回': 'rejected', '待同步': 'sync_pending', '同步失敗': 'sync_failed' })[v] || ''; }, confirmationLabel(v) { return ({ confirmed: '已確認', rejected: '已退回' })[v] || '已完成'; }, confirmationClass(v) { return v === 'rejected' ? 'red' : 'green'; }, syncLabel(v) { return ({ not_synced: '未同步', pending: '待同步', synced: '已同步', failed: '同步失敗' })[v] || '未同步'; }, syncClass(v) { return v === 'synced' ? 'green' : v === 'failed' ? 'red' : 'orange'; }, paymentMethodLabel(v) { return ({ bank_transfer: '銀行轉帳', online_transfer: '網上轉帳', cheque: '支票', cash: '現金', online_banking: '網上銀行' })[v] || v || '—'; }, monthLabel(v) { return v ? String(v).slice(0, 7) : '—'; }, formatDateTime(v) { return v ? String(v).replace('T', ' ').slice(0, 19) : '—'; }, fileSize(v) { if (!v) return '—'; return v >= 1024 * 1024 ? `${(v / 1024 / 1024).toFixed(1)} MB` : `${Math.ceil(v / 1024)} KB`; }, money(v) { return Number(v || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
}
};
</script>

<style scoped>
.history-actions{display:flex;gap:10px;align-items:center}.selected-transaction{display:inline-flex;align-items:center;max-width:230px;height:30px;padding:0 10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;border:1px solid #dbe5ef;border-radius:8px;background:#f5f8fb;color:#315879;font-size:12px}.selected-transaction.empty{color:#8493a3;background:#fafbfd}.history-actions .primary-btn,.history-actions .receipt-btn{display:inline-flex;align-items:center;justify-content:center;min-width:132px;height:40px;padding:0 16px;border-radius:10px;font-size:14px;font-weight:700;line-height:1;transition:background .18s ease,border-color .18s ease,box-shadow .18s ease,transform .18s ease}.history-actions .primary-btn{border:1px solid #dda400;background:linear-gradient(180deg,#f9c21b,#e9aa00);color:#fff;box-shadow:0 3px 8px rgba(211,151,0,.2)}.history-actions .primary-btn:hover:not(:disabled){background:linear-gradient(180deg,#ffd044,#edb000);box-shadow:0 5px 12px rgba(211,151,0,.28);transform:translateY(-1px)}.history-actions .receipt-btn{border:1px solid #24588f;background:#fff;color:#1b548b;text-decoration:none;box-shadow:0 2px 6px rgba(33,82,135,.08)}.history-actions .receipt-btn:hover:not(:disabled){background:#f2f7fc;border-color:#174877;box-shadow:0 4px 10px rgba(33,82,135,.14);transform:translateY(-1px)}.history-actions .primary-btn:disabled,.history-actions .receipt-btn:disabled{opacity:.55;cursor:not-allowed;box-shadow:none;transform:none}.finance-proof-link{display:inline-flex;align-items:center;justify-content:center;min-width:78px;height:30px;padding:0 10px;border:1px solid #b7cfee;border-radius:7px;background:#f5f9ff;color:#185a97;font-size:11px;font-weight:700;line-height:1;white-space:nowrap;transition:background .18s ease,border-color .18s ease,color .18s ease}.finance-proof-link:hover{background:#e9f2ff;border-color:#6f9fda;color:#103f73}.finance-proof-link.receipt-link{min-width:48px;margin-left:6px;background:#fff;color:#24588f;text-decoration:none}.finance-proof-link.receipt-link:hover{background:#f2f7fc}.rent-history-filters{display:flex;gap:10px;align-items:end;padding:12px 0}.rent-history-filters label{display:grid;gap:4px;color:#52657a;font-size:12px}.rent-history-filters input{border:1px solid #cdd8e4;border-radius:6px;padding:8px 9px}.rent-history-filters>button{border:1px solid #cdd8e4;background:#fff;border-radius:6px;padding:8px 12px}
</style>
<style scoped>
.finance-document-button{display:inline-flex;align-items:center;justify-content:center;min-height:30px;padding:0 10px;border:1px solid #b7cfee;border-radius:7px;background:#f7fbff;color:#185a97;font-size:11px;text-decoration:none;white-space:nowrap}.finance-document-button:hover{background:#eaf3ff;border-color:#6f9fda}
</style>
