import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const workspace = readFileSync(new URL('../src/components/AdminRentalMandateWorkspace.vue', import.meta.url), 'utf8');
const i18n = readFileSync(new URL('../src/i18n/index.js', import.meta.url), 'utf8');
const documentService = readFileSync(new URL('../../backend/src/main/java/com/ccps/backend/service/AdminRentalMandateDocumentService.java', import.meta.url), 'utf8');
const signatureService = readFileSync(new URL('../../backend/src/main/java/com/ccps/backend/service/ElectronicSignatureService.java', import.meta.url), 'utf8');
const signatureMapper = readFileSync(new URL('../../backend/src/main/java/com/ccps/backend/mapper/ElectronicSignatureMapper.java', import.meta.url), 'utf8');

test('authorization signing stays independent from mandate activation', () => {
  assert.match(workspace, /signedAuthorizationUploadHint/);
  assert.match(i18n, /signedAuthorizationUploadHint: \['[^']+', '[^']+', '[^']+'\]/);
  assert.match(i18n, /authorizationUploaded: \['[^']+', '[^']+', '[^']+'\]/);
  assert.match(i18n, /authorizationStepComplete: \['[^']+', '[^']+', '[^']+'\]/);
  assert.doesNotMatch(workspace, /openAuthorizationGenerator\(item\)/);
  assert.match(workspace, /generateAdminContractTemplate\('authorization'/);
  assert.match(workspace, /uploadAdminRentalMandateDocument\(this\.selected\.id, 'authorization_draft'/);
  assert.match(workspace, /authorizationWorkspaceOpen/);
  assert.match(workspace, /startOnlineSigning/);
  assert.match(workspace, /doc\.relationType !== 'signed_contract'/);
  assert.match(workspace, /if \(doc\?\.relationType === 'signed_contract'/);
  assert.doesNotMatch(workspace, /selected\.status !== 'active'/);
  assert.doesNotMatch(workspace, /this\.selected\?\.status === 'active'/);
  assert.doesNotMatch(workspace, /submitAdminRentalMandate/);
  assert.doesNotMatch(workspace, /reviewAdminRentalMandate/);
  assert.doesNotMatch(workspace, /openReview/);
  assert.doesNotMatch(workspace, /reviewing/);
  assert.doesNotMatch(workspace, /authorizationRequiredBeforeApproval/);
  assert.doesNotMatch(workspace, /authorizationStepReview/);
  assert.doesNotMatch(workspace, /manageMandate/);
  assert.doesNotMatch(workspace, /class="workflow-card"/);
  assert.match(workspace, /&& !hasAuthorization/);
  assert.match(workspace, /:has\(\.modal-backdrop\) \.detail-panel/);
  assert.match(workspace, /workflowPending/);
  assert.match(workspace, /startDocumentRefresh\(\)/);
  assert.match(workspace, /setInterval\(\(\) => this\.refreshSelectedDocuments\(\), 4000\)/);
  assert.match(workspace, /documentsLoading/);
  assert.match(workspace, /Promise\.all\(\[fetchAdminRentalMandateHistory/);
  assert.match(i18n, /loadingDocuments: \['[^']+', '[^']+', '[^']+'\]/);
  assert.match(workspace, /beforeUnmount\(\)/);
  assert.match(documentService, /authorization_draft/);
  assert.match(signatureMapper, /insertSignedMandateDocumentLink/);
  assert.match(signatureService, /insertSignedMandateDocumentLink\(signed\.getId\(\), row\.getEntityId\(\), signedRelation/);
});
